/**
 * Workflow Service
 *
 * Frontend service for workflow management:
 * - Pending actions across all business processes
 * - Recent activity feed
 * - Workflow statistics
 */

import authService from './authService';
import { API_BASE_URL } from '../config/api';

const workflowService = {
  /**
   * Get pending actions across all workflows
   * Returns high priority and normal priority tasks
   *
   * @param {Object} params - Optional query parameters
   * @param {string} params.project_id - Filter by project ID
   * @returns {Promise<Object>} { high: [], normal: [], stats: {} }
   */
  async getPendingActions(params = {}) {
    try {
      const queryParams = new URLSearchParams();
      if (params.project_id) queryParams.append('project_id', params.project_id);
      const queryString = queryParams.toString();
      const url = `${API_BASE_URL}/workflow/pending-actions${queryString ? `?${queryString}` : ''}`;

      const data = await authService.makeAuthenticatedRequest(
        url,
        {
          method: 'GET'
        }
      );

      // Check if backend returned success
      if (data && data.success && data.data) {
        return {
          success: true,
          data: data.data
        };
      } else if (data && data.success === false) {
        // Backend returned an error
        throw new Error(data.message || data.error || 'Backend error');
      } else {
        throw new Error('Invalid response format');
      }
    } catch (error) {
      console.error('Error fetching pending actions:', error);
      return {
        success: false,
        error: error.message || 'Failed to fetch pending actions',
        data: { high: [], normal: [], stats: { totalPending: 0, highPriority: 0, normalPriority: 0 } }
      };
    }
  },

  /**
   * Get recent activity feed
   * Returns last N activities across all workflows
   *
   * @param {number} limit - Number of activities to return (default: 50)
   * @param {Object} params - Optional query parameters
   * @param {string} params.project_id - Filter by project ID
   * @returns {Promise<Object>} { activities: [], total: number }
   */
  async getActivityFeed(limit = 50, params = {}) {
    try {
      const queryParams = new URLSearchParams();
      queryParams.append('limit', limit);
      if (params.project_id) queryParams.append('project_id', params.project_id);
      const url = `${API_BASE_URL}/workflow/activity?${queryParams.toString()}`;

      const data = await authService.makeAuthenticatedRequest(
        url,
        {
          method: 'GET'
        }
      );

      // Check if backend returned success
      if (data && data.success && data.data) {
        return {
          success: true,
          data: data.data
        };
      } else if (data && data.success === false) {
        throw new Error(data.message || data.error || 'Backend error');
      } else {
        throw new Error('Invalid response format');
      }
    } catch (error) {
      console.error('Error fetching activity feed:', error);
      return {
        success: false,
        error: error.message || 'Failed to fetch activity feed',
        data: { activities: [], total: 0 }
      };
    }
  },

  /**
   * Get workflow statistics
   * Returns quick stats for dashboard widgets
   *
   * @param {Object} params - Optional query parameters
   * @param {string} params.project_id - Filter by project ID
   * @returns {Promise<Object>} { collections: {}, purchaseOrders: {}, invoices: {}, contracts: {} }
   */
  async getWorkflowStats(params = {}) {
    try {
      const queryParams = new URLSearchParams();
      if (params.project_id) queryParams.append('project_id', params.project_id);
      const queryString = queryParams.toString();
      const url = `${API_BASE_URL}/workflow/stats${queryString ? `?${queryString}` : ''}`;

      const data = await authService.makeAuthenticatedRequest(
        url,
        {
          method: 'GET'
        }
      );

      // Check if backend returned success
      if (data && data.success && data.data) {
        return {
          success: true,
          data: data.data
        };
      } else if (data && data.success === false) {
        throw new Error(data.message || data.error || 'Backend error');
      } else {
        throw new Error('Invalid response format');
      }
    } catch (error) {
      console.error('Error fetching workflow stats:', error);
      return {
        success: false,
        error: error.message || 'Failed to fetch workflow stats',
        data: {
          collections: { total: 0, pendingWCN: 0, finalized: 0 },
          purchaseOrders: { total: 0, pendingReceipt: 0, received: 0, autoGenerated: 0 },
          invoices: { total: 0, unpaid: 0, totalValue: 0, outstandingAmount: 0 }
        }
      };
    }
  },

  /**
   * Get live notifications for dashboard/header bell
   * Returns condensed summary of urgent items across all modules
   *
   * @param {number} limit - Number of notifications to return (default: 10)
   * @param {Object} params - Optional query parameters
   * @param {string} params.project_id - Filter by project ID
   * @returns {Promise<Object>} { notifications: [], total: number, hasUrgent: boolean }
   */
  async getNotifications(limit = 10, params = {}) {
    try {
      const queryParams = new URLSearchParams();
      queryParams.append('limit', limit);
      if (params.project_id) queryParams.append('project_id', params.project_id);
      const url = `${API_BASE_URL}/workflow/notifications?${queryParams.toString()}`;

      const data = await authService.makeAuthenticatedRequest(
        url,
        {
          method: 'GET'
        }
      );

      // Check if backend returned success
      if (data && data.success && data.data) {
        return {
          success: true,
          data: data.data
        };
      } else if (data && data.success === false) {
        throw new Error(data.message || data.error || 'Backend error');
      } else {
        throw new Error('Invalid response format');
      }
    } catch (error) {
      console.error('Error fetching notifications:', error);
      return {
        success: false,
        error: error.message || 'Failed to fetch notifications',
        data: { notifications: [], total: 0, hasUrgent: false }
      };
    }
  }
};

export default workflowService;
