/**
 * Roles & Permissions Configuration — Simplified.
 * Each module: MANAGE_X (implies all), VIEW_X, CREATE_X, EDIT_X, DELETE_X.
 * MANAGE_X is the parent; all others are children.
 */

export const PERMISSIONS = {
  // User Management
  MANAGE_USERS: 'MANAGE_USERS', VIEW_USERS: 'VIEW_USERS', CREATE_USERS: 'CREATE_USERS', EDIT_USERS: 'EDIT_USERS', DELETE_USERS: 'DELETE_USERS',
  // Role Management
  MANAGE_ROLES: 'MANAGE_ROLES', VIEW_ROLES: 'VIEW_ROLES',
  // Company Management
  MANAGE_COMPANIES: 'MANAGE_COMPANIES', VIEW_COMPANIES: 'VIEW_COMPANIES', SWITCH_COMPANIES: 'SWITCH_COMPANIES',
  // Suppliers
  MANAGE_SUPPLIERS: 'MANAGE_SUPPLIERS', VIEW_SUPPLIERS: 'VIEW_SUPPLIERS', CREATE_SUPPLIERS: 'CREATE_SUPPLIERS', EDIT_SUPPLIERS: 'EDIT_SUPPLIERS', DELETE_SUPPLIERS: 'DELETE_SUPPLIERS',
  // Customers
  MANAGE_CUSTOMERS: 'MANAGE_CUSTOMERS', VIEW_CUSTOMERS: 'VIEW_CUSTOMERS', CREATE_CUSTOMERS: 'CREATE_CUSTOMERS', EDIT_CUSTOMERS: 'EDIT_CUSTOMERS', DELETE_CUSTOMERS: 'DELETE_CUSTOMERS',
  // Materials
  MANAGE_MATERIALS: 'MANAGE_MATERIALS', VIEW_MATERIALS: 'VIEW_MATERIALS', CREATE_MATERIALS: 'CREATE_MATERIALS', EDIT_MATERIALS: 'EDIT_MATERIALS', DELETE_MATERIALS: 'DELETE_MATERIALS',
  // Inventory
  MANAGE_INVENTORY: 'MANAGE_INVENTORY', VIEW_INVENTORY: 'VIEW_INVENTORY', EDIT_INVENTORY: 'EDIT_INVENTORY',
  // Contracts
  MANAGE_CONTRACTS: 'MANAGE_CONTRACTS', VIEW_CONTRACTS: 'VIEW_CONTRACTS', CREATE_CONTRACTS: 'CREATE_CONTRACTS', EDIT_CONTRACTS: 'EDIT_CONTRACTS', DELETE_CONTRACTS: 'DELETE_CONTRACTS',
  // Collections & WCN (includes callouts, WCN finalization)
  MANAGE_COLLECTIONS: 'MANAGE_COLLECTIONS', VIEW_COLLECTIONS: 'VIEW_COLLECTIONS', CREATE_COLLECTIONS: 'CREATE_COLLECTIONS', EDIT_COLLECTIONS: 'EDIT_COLLECTIONS', DELETE_COLLECTIONS: 'DELETE_COLLECTIONS',
  // Sales
  MANAGE_SALES: 'MANAGE_SALES', VIEW_SALES: 'VIEW_SALES', CREATE_SALES: 'CREATE_SALES', EDIT_SALES: 'EDIT_SALES', DELETE_SALES: 'DELETE_SALES',
  // Purchase (includes POs, amendments, PO expenses)
  MANAGE_PURCHASE: 'MANAGE_PURCHASE', VIEW_PURCHASE: 'VIEW_PURCHASE', CREATE_PURCHASE: 'CREATE_PURCHASE', EDIT_PURCHASE: 'EDIT_PURCHASE', DELETE_PURCHASE: 'DELETE_PURCHASE',
  // Wastage
  MANAGE_WASTAGE: 'MANAGE_WASTAGE', VIEW_WASTAGE: 'VIEW_WASTAGE', CREATE_WASTAGE: 'CREATE_WASTAGE', EDIT_WASTAGE: 'EDIT_WASTAGE', DELETE_WASTAGE: 'DELETE_WASTAGE',
  // Petty Cash (includes cards and expenses)
  MANAGE_PETTY_CASH: 'MANAGE_PETTY_CASH', VIEW_PETTY_CASH: 'VIEW_PETTY_CASH', CREATE_PETTY_CASH: 'CREATE_PETTY_CASH', EDIT_PETTY_CASH: 'EDIT_PETTY_CASH', DELETE_PETTY_CASH: 'DELETE_PETTY_CASH',
  // Finance (expenses, categories, transactions)
  MANAGE_FINANCE: 'MANAGE_FINANCE', VIEW_FINANCE: 'VIEW_FINANCE', CREATE_FINANCE: 'CREATE_FINANCE', EDIT_FINANCE: 'EDIT_FINANCE', DELETE_FINANCE: 'DELETE_FINANCE',
  // Invoices
  MANAGE_INVOICES: 'MANAGE_INVOICES', VIEW_INVOICES: 'VIEW_INVOICES', CREATE_INVOICES: 'CREATE_INVOICES', EDIT_INVOICES: 'EDIT_INVOICES', DELETE_INVOICES: 'DELETE_INVOICES',
  // Banking (bank accounts, transactions)
  MANAGE_BANKING: 'MANAGE_BANKING', VIEW_BANKING: 'VIEW_BANKING', CREATE_BANKING: 'CREATE_BANKING', EDIT_BANKING: 'EDIT_BANKING', DELETE_BANKING: 'DELETE_BANKING',
  // Reports
  MANAGE_REPORTS: 'MANAGE_REPORTS', VIEW_REPORTS: 'VIEW_REPORTS',
  // Settings (includes audit logs, branches, system config)
  MANAGE_SETTINGS: 'MANAGE_SETTINGS', VIEW_SETTINGS: 'VIEW_SETTINGS',
  // Backups (super admin only)
  MANAGE_BACKUPS: 'MANAGE_BACKUPS',
  // Projects
  MANAGE_PROJECTS: 'MANAGE_PROJECTS', VIEW_PROJECTS: 'VIEW_PROJECTS', CREATE_PROJECTS: 'CREATE_PROJECTS', EDIT_PROJECTS: 'EDIT_PROJECTS', DELETE_PROJECTS: 'DELETE_PROJECTS',
  // Employees
  MANAGE_EMPLOYEES: 'MANAGE_EMPLOYEES', VIEW_EMPLOYEES: 'VIEW_EMPLOYEES', CREATE_EMPLOYEES: 'CREATE_EMPLOYEES', EDIT_EMPLOYEES: 'EDIT_EMPLOYEES', DELETE_EMPLOYEES: 'DELETE_EMPLOYEES',
  // Vehicles (includes vehicle types)
  MANAGE_VEHICLES: 'MANAGE_VEHICLES', VIEW_VEHICLES: 'VIEW_VEHICLES', CREATE_VEHICLES: 'CREATE_VEHICLES', EDIT_VEHICLES: 'EDIT_VEHICLES', DELETE_VEHICLES: 'DELETE_VEHICLES',
  // Tank Logs
  MANAGE_TANK_LOGS: 'MANAGE_TANK_LOGS', VIEW_TANK_LOGS: 'VIEW_TANK_LOGS', CREATE_TANK_LOGS: 'CREATE_TANK_LOGS', EDIT_TANK_LOGS: 'EDIT_TANK_LOGS', DELETE_TANK_LOGS: 'DELETE_TANK_LOGS',
  // Expense Sheets
  MANAGE_EXPENSE_SHEETS: 'MANAGE_EXPENSE_SHEETS', VIEW_EXPENSE_SHEETS: 'VIEW_EXPENSE_SHEETS', CREATE_EXPENSE_SHEETS: 'CREATE_EXPENSE_SHEETS', EDIT_EXPENSE_SHEETS: 'EDIT_EXPENSE_SHEETS', DELETE_EXPENSE_SHEETS: 'DELETE_EXPENSE_SHEETS',
}

/** MANAGE_X → children it implies (mirrors backend permissionsHierarchy) */
export const PARENT_PERMISSIONS = {
  MANAGE_USERS:          ['VIEW_USERS',          'CREATE_USERS',          'EDIT_USERS',          'DELETE_USERS'],
  MANAGE_ROLES:          ['VIEW_ROLES'],
  MANAGE_COMPANIES:      ['VIEW_COMPANIES',       'SWITCH_COMPANIES'],
  MANAGE_SUPPLIERS:      ['VIEW_SUPPLIERS',       'CREATE_SUPPLIERS',      'EDIT_SUPPLIERS',      'DELETE_SUPPLIERS'],
  MANAGE_CUSTOMERS:      ['VIEW_CUSTOMERS',       'CREATE_CUSTOMERS',      'EDIT_CUSTOMERS',      'DELETE_CUSTOMERS'],
  MANAGE_MATERIALS:      ['VIEW_MATERIALS',       'CREATE_MATERIALS',      'EDIT_MATERIALS',      'DELETE_MATERIALS'],
  MANAGE_INVENTORY:      ['VIEW_INVENTORY',       'EDIT_INVENTORY'],
  MANAGE_CONTRACTS:      ['VIEW_CONTRACTS',       'CREATE_CONTRACTS',      'EDIT_CONTRACTS',      'DELETE_CONTRACTS'],
  MANAGE_COLLECTIONS:    ['VIEW_COLLECTIONS',     'CREATE_COLLECTIONS',    'EDIT_COLLECTIONS',    'DELETE_COLLECTIONS'],
  MANAGE_SALES:          ['VIEW_SALES',           'CREATE_SALES',          'EDIT_SALES',          'DELETE_SALES'],
  MANAGE_PURCHASE:       ['VIEW_PURCHASE',        'CREATE_PURCHASE',       'EDIT_PURCHASE',       'DELETE_PURCHASE'],
  MANAGE_WASTAGE:        ['VIEW_WASTAGE',         'CREATE_WASTAGE',        'EDIT_WASTAGE',        'DELETE_WASTAGE'],
  MANAGE_PETTY_CASH:     ['VIEW_PETTY_CASH',      'CREATE_PETTY_CASH',     'EDIT_PETTY_CASH',     'DELETE_PETTY_CASH'],
  MANAGE_FINANCE:        ['VIEW_FINANCE',         'CREATE_FINANCE',        'EDIT_FINANCE',        'DELETE_FINANCE'],
  MANAGE_INVOICES:       ['VIEW_INVOICES',        'CREATE_INVOICES',       'EDIT_INVOICES',       'DELETE_INVOICES'],
  MANAGE_BANKING:        ['VIEW_BANKING',         'CREATE_BANKING',        'EDIT_BANKING',        'DELETE_BANKING'],
  MANAGE_REPORTS:        ['VIEW_REPORTS'],
  MANAGE_SETTINGS:       ['VIEW_SETTINGS',        'MANAGE_BACKUPS'],
  MANAGE_PROJECTS:       ['VIEW_PROJECTS',        'CREATE_PROJECTS',       'EDIT_PROJECTS',       'DELETE_PROJECTS'],
  MANAGE_EMPLOYEES:      ['VIEW_EMPLOYEES',       'CREATE_EMPLOYEES',      'EDIT_EMPLOYEES',      'DELETE_EMPLOYEES'],
  MANAGE_VEHICLES:       ['VIEW_VEHICLES',        'CREATE_VEHICLES',       'EDIT_VEHICLES',       'DELETE_VEHICLES'],
  MANAGE_TANK_LOGS:      ['VIEW_TANK_LOGS',       'CREATE_TANK_LOGS',      'EDIT_TANK_LOGS',      'DELETE_TANK_LOGS'],
  MANAGE_EXPENSE_SHEETS: ['VIEW_EXPENSE_SHEETS',  'CREATE_EXPENSE_SHEETS', 'EDIT_EXPENSE_SHEETS', 'DELETE_EXPENSE_SHEETS'],
}

export const ROLES = {
  SUPER_ADMIN:    { id: 'super_admin',    label: 'Super Admin',    level: 10 },
  COMPANY_ADMIN:  { id: 'company_admin',  label: 'Company Admin',  level: 9  },
  MANAGER:        { id: 'manager',        label: 'Manager',        level: 7  },
  SALES_STAFF:    { id: 'sales_staff',    label: 'Sales Staff',    level: 4  },
  PURCHASE_STAFF: { id: 'purchase_staff', label: 'Purchase Staff', level: 4  },
  ACCOUNTS_STAFF: { id: 'accounts_staff', label: 'Accounts Staff', level: 4  },
}

// Kept for backward compatibility with components that reference USER_ROLES
export const USER_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  COMPANY_ADMIN: 'COMPANY_ADMIN',
  MANAGER: 'MANAGER',
  SALES_STAFF: 'SALES_STAFF',
  PURCHASE_STAFF: 'PURCHASE_STAFF',
  ACCOUNTS_STAFF: 'ACCOUNTS_STAFF'
}

// Kept for backward compatibility with usePermissions.js
export const ROLE_HIERARCHY = {
  SUPER_ADMIN: 10,
  COMPANY_ADMIN: 9,
  MANAGER: 7,
  SALES_STAFF: 4,
  PURCHASE_STAFF: 4,
  ACCOUNTS_STAFF: 4
}

export const ROLE_PERMISSIONS = {
  SUPER_ADMIN: Object.values(PERMISSIONS),

  COMPANY_ADMIN: [
    'MANAGE_USERS', 'MANAGE_ROLES',
    'MANAGE_SUPPLIERS', 'MANAGE_CUSTOMERS', 'MANAGE_MATERIALS', 'MANAGE_INVENTORY',
    'MANAGE_CONTRACTS', 'MANAGE_COLLECTIONS', 'MANAGE_SALES', 'MANAGE_PURCHASE',
    'MANAGE_WASTAGE', 'MANAGE_PETTY_CASH', 'MANAGE_FINANCE', 'MANAGE_INVOICES',
    'MANAGE_BANKING', 'MANAGE_REPORTS', 'MANAGE_SETTINGS',
    'MANAGE_PROJECTS', 'MANAGE_EMPLOYEES', 'MANAGE_VEHICLES', 'MANAGE_TANK_LOGS', 'MANAGE_EXPENSE_SHEETS',
  ],

  MANAGER: [
    'MANAGE_SUPPLIERS', 'MANAGE_CUSTOMERS', 'MANAGE_MATERIALS', 'MANAGE_INVENTORY',
    'MANAGE_CONTRACTS', 'MANAGE_COLLECTIONS', 'MANAGE_SALES', 'MANAGE_PURCHASE',
    'MANAGE_WASTAGE', 'MANAGE_PETTY_CASH', 'MANAGE_FINANCE', 'MANAGE_INVOICES',
    'MANAGE_PROJECTS', 'MANAGE_EMPLOYEES', 'MANAGE_VEHICLES', 'MANAGE_TANK_LOGS', 'MANAGE_EXPENSE_SHEETS',
    'VIEW_BANKING', 'VIEW_REPORTS', 'VIEW_SETTINGS', 'VIEW_USERS', 'VIEW_ROLES',
  ],

  SALES_STAFF: [
    'VIEW_CUSTOMERS', 'VIEW_SUPPLIERS', 'VIEW_MATERIALS', 'VIEW_INVENTORY',
    'VIEW_CONTRACTS', 'VIEW_COLLECTIONS',
    'MANAGE_SALES', 'VIEW_PURCHASE',
    'VIEW_INVOICES', 'VIEW_REPORTS',
  ],

  PURCHASE_STAFF: [
    'MANAGE_SUPPLIERS', 'VIEW_CUSTOMERS', 'VIEW_MATERIALS', 'MANAGE_INVENTORY',
    'MANAGE_CONTRACTS', 'MANAGE_COLLECTIONS',
    'MANAGE_PURCHASE', 'VIEW_SALES', 'MANAGE_WASTAGE',
    'VIEW_INVOICES', 'VIEW_REPORTS',
  ],

  ACCOUNTS_STAFF: [
    'VIEW_SUPPLIERS', 'VIEW_CUSTOMERS', 'VIEW_MATERIALS', 'VIEW_INVENTORY',
    'VIEW_SALES', 'VIEW_PURCHASE',
    'MANAGE_PETTY_CASH', 'MANAGE_FINANCE', 'MANAGE_INVOICES',
    'VIEW_BANKING', 'VIEW_REPORTS',
  ],
}

export const getRoleDisplayName = (role) => {
  const displayNames = {
    SUPER_ADMIN: 'Super Admin',
    COMPANY_ADMIN: 'Company Admin',
    MANAGER: 'Manager',
    SALES_STAFF: 'Sales Staff',
    PURCHASE_STAFF: 'Purchase Staff',
    ACCOUNTS_STAFF: 'Accounts Staff'
  }
  return displayNames[role] || role
}

export const getRoleColor = (role) => {
  const colors = {
    SUPER_ADMIN: '#dc2626',    // red
    COMPANY_ADMIN: '#7c3aed', // purple
    MANAGER: '#059669',       // green
    SALES_STAFF: '#3b82f6',   // blue
    PURCHASE_STAFF: '#f59e0b', // amber
    ACCOUNTS_STAFF: '#6b7280' // gray
  }
  return colors[role] || '#6b7280'
}
