// Role-based Access Control Configuration
export const USER_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  COMPANY_ADMIN: 'COMPANY_ADMIN', 
  MANAGER: 'MANAGER',
  SALES: 'SALES',
  PURCHASE: 'PURCHASE',
  ACCOUNTS: 'ACCOUNTS'
}

export const ROLE_HIERARCHY = {
  [USER_ROLES.SUPER_ADMIN]: 6,
  [USER_ROLES.COMPANY_ADMIN]: 5,
  [USER_ROLES.MANAGER]: 4,
  [USER_ROLES.SALES]: 3,
  [USER_ROLES.PURCHASE]: 3,
  [USER_ROLES.ACCOUNTS]: 3
}

export const PERMISSIONS = {
  // User Management
  MANAGE_USERS: 'MANAGE_USERS',
  VIEW_USERS: 'VIEW_USERS',
  ASSIGN_ROLES: 'ASSIGN_ROLES',
  
  // Company Management
  MANAGE_COMPANIES: 'MANAGE_COMPANIES',
  VIEW_COMPANIES: 'VIEW_COMPANIES',
  SWITCH_COMPANIES: 'SWITCH_COMPANIES',
  
  // Customer/Supplier Management
  MANAGE_CUSTOMERS: 'MANAGE_CUSTOMERS',
  VIEW_CUSTOMERS: 'VIEW_CUSTOMERS',
  MANAGE_SUPPLIERS: 'MANAGE_SUPPLIERS',
  VIEW_SUPPLIERS: 'VIEW_SUPPLIERS',
  
  // Inventory Management
  MANAGE_INVENTORY: 'MANAGE_INVENTORY',
  VIEW_INVENTORY: 'VIEW_INVENTORY',
  UPDATE_STOCK: 'UPDATE_STOCK',
  
  // Sales Management
  CREATE_SALES: 'CREATE_SALES',
  VIEW_SALES: 'VIEW_SALES',
  EDIT_SALES: 'EDIT_SALES',
  DELETE_SALES: 'DELETE_SALES',
  APPROVE_SALES: 'APPROVE_SALES',
  
  // Purchase Management
  CREATE_PURCHASE: 'CREATE_PURCHASE',
  VIEW_PURCHASE: 'VIEW_PURCHASE',
  EDIT_PURCHASE: 'EDIT_PURCHASE',
  DELETE_PURCHASE: 'DELETE_PURCHASE',
  APPROVE_PURCHASE: 'APPROVE_PURCHASE',
  
  // Purchase Order Management
  CREATE_PURCHASE_ORDER: 'CREATE_PURCHASE_ORDER',
  VIEW_PURCHASE_ORDER: 'VIEW_PURCHASE_ORDER',
  EDIT_PURCHASE_ORDER: 'EDIT_PURCHASE_ORDER',
  DELETE_PURCHASE_ORDER: 'DELETE_PURCHASE_ORDER',
  APPROVE_PURCHASE_ORDER: 'APPROVE_PURCHASE_ORDER',
  
  // Vendor Management
  MANAGE_VENDORS: 'MANAGE_VENDORS',
  VIEW_VENDORS: 'VIEW_VENDORS',
  
  // Contract Management
  MANAGE_CONTRACTS: 'MANAGE_CONTRACTS',
  VIEW_CONTRACTS: 'VIEW_CONTRACTS',
  APPROVE_CONTRACTS: 'APPROVE_CONTRACTS',
  
  // Financial Management
  VIEW_FINANCIALS: 'VIEW_FINANCIALS',
  MANAGE_EXPENSES: 'MANAGE_EXPENSES',
  APPROVE_EXPENSES: 'APPROVE_EXPENSES',
  MANAGE_PETTY_CASH: 'MANAGE_PETTY_CASH',
  VIEW_PROFIT_LOSS: 'VIEW_PROFIT_LOSS',
  
  // Reporting
  VIEW_REPORTS: 'VIEW_REPORTS',
  EXPORT_REPORTS: 'EXPORT_REPORTS',
  CREATE_CUSTOM_REPORTS: 'CREATE_CUSTOM_REPORTS',
  
  // Invoice Management
  CREATE_INVOICES: 'CREATE_INVOICES',
  VIEW_INVOICES: 'VIEW_INVOICES',
  EDIT_INVOICES: 'EDIT_INVOICES',
  
  // System Settings
  MANAGE_SETTINGS: 'MANAGE_SETTINGS',
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',
  
  // Wastage Management
  VIEW_WASTAGE: 'VIEW_WASTAGE',
  CREATE_WASTAGE: 'CREATE_WASTAGE',
  EDIT_WASTAGE: 'EDIT_WASTAGE',
  DELETE_WASTAGE: 'DELETE_WASTAGE',
  APPROVE_WASTAGE: 'APPROVE_WASTAGE'
}

export const ROLE_PERMISSIONS = {
  [USER_ROLES.SUPER_ADMIN]: [
    // All permissions
    ...Object.values(PERMISSIONS)
  ],
  
  [USER_ROLES.COMPANY_ADMIN]: [
    // User Management (within company)
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.ASSIGN_ROLES,
    
    // Company Management (own company only)
    PERMISSIONS.VIEW_COMPANIES,
    
    // Customer/Supplier Management
    PERMISSIONS.MANAGE_CUSTOMERS,
    PERMISSIONS.VIEW_CUSTOMERS,
    PERMISSIONS.MANAGE_SUPPLIERS,
    PERMISSIONS.VIEW_SUPPLIERS,
    
    // Inventory Management
    PERMISSIONS.MANAGE_INVENTORY,
    PERMISSIONS.VIEW_INVENTORY,
    PERMISSIONS.UPDATE_STOCK,
    
    // Sales Management
    PERMISSIONS.CREATE_SALES,
    PERMISSIONS.VIEW_SALES,
    PERMISSIONS.EDIT_SALES,
    PERMISSIONS.DELETE_SALES,
    PERMISSIONS.APPROVE_SALES,
    
    // Purchase Management
    PERMISSIONS.CREATE_PURCHASE,
    PERMISSIONS.VIEW_PURCHASE,
    PERMISSIONS.EDIT_PURCHASE,
    PERMISSIONS.DELETE_PURCHASE,
    PERMISSIONS.APPROVE_PURCHASE,
    
    // Purchase Order Management
    PERMISSIONS.CREATE_PURCHASE_ORDER,
    PERMISSIONS.VIEW_PURCHASE_ORDER,
    PERMISSIONS.EDIT_PURCHASE_ORDER,
    PERMISSIONS.DELETE_PURCHASE_ORDER,
    PERMISSIONS.APPROVE_PURCHASE_ORDER,
    
    // Vendor Management
    PERMISSIONS.MANAGE_VENDORS,
    PERMISSIONS.VIEW_VENDORS,
    
    // Contract Management
    PERMISSIONS.MANAGE_CONTRACTS,
    PERMISSIONS.VIEW_CONTRACTS,
    PERMISSIONS.APPROVE_CONTRACTS,
    
    // Financial Management
    PERMISSIONS.VIEW_FINANCIALS,
    PERMISSIONS.MANAGE_EXPENSES,
    PERMISSIONS.APPROVE_EXPENSES,
    PERMISSIONS.MANAGE_PETTY_CASH,
    PERMISSIONS.VIEW_PROFIT_LOSS,
    
    // Reporting
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.EXPORT_REPORTS,
    PERMISSIONS.CREATE_CUSTOM_REPORTS,
    
    // Invoice Management
    PERMISSIONS.CREATE_INVOICES,
    PERMISSIONS.VIEW_INVOICES,
    PERMISSIONS.EDIT_INVOICES,
    
    // Settings
    PERMISSIONS.MANAGE_SETTINGS,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    
    // Wastage Management
    PERMISSIONS.VIEW_WASTAGE,
    PERMISSIONS.CREATE_WASTAGE,
    PERMISSIONS.EDIT_WASTAGE,
    PERMISSIONS.DELETE_WASTAGE,
    PERMISSIONS.APPROVE_WASTAGE
  ],
  
  [USER_ROLES.MANAGER]: [
    // User Management (view only)
    PERMISSIONS.VIEW_USERS,
    
    // Customer/Supplier Management
    PERMISSIONS.MANAGE_CUSTOMERS,
    PERMISSIONS.VIEW_CUSTOMERS,
    PERMISSIONS.MANAGE_SUPPLIERS,
    PERMISSIONS.VIEW_SUPPLIERS,
    
    // Inventory Management
    PERMISSIONS.MANAGE_INVENTORY,
    PERMISSIONS.VIEW_INVENTORY,
    PERMISSIONS.UPDATE_STOCK,
    
    // Sales Management
    PERMISSIONS.CREATE_SALES,
    PERMISSIONS.VIEW_SALES,
    PERMISSIONS.EDIT_SALES,
    PERMISSIONS.APPROVE_SALES,
    
    // Purchase Management
    PERMISSIONS.CREATE_PURCHASE,
    PERMISSIONS.VIEW_PURCHASE,
    PERMISSIONS.EDIT_PURCHASE,
    PERMISSIONS.APPROVE_PURCHASE,
    
    // Purchase Order Management
    PERMISSIONS.CREATE_PURCHASE_ORDER,
    PERMISSIONS.VIEW_PURCHASE_ORDER,
    PERMISSIONS.EDIT_PURCHASE_ORDER,
    PERMISSIONS.APPROVE_PURCHASE_ORDER,
    
    // Vendor Management
    PERMISSIONS.MANAGE_VENDORS,
    PERMISSIONS.VIEW_VENDORS,
    
    // Contract Management
    PERMISSIONS.VIEW_CONTRACTS,
    PERMISSIONS.APPROVE_CONTRACTS,
    
    // Financial Management
    PERMISSIONS.VIEW_FINANCIALS,
    PERMISSIONS.MANAGE_EXPENSES,
    PERMISSIONS.APPROVE_EXPENSES,
    PERMISSIONS.VIEW_PROFIT_LOSS,
    
    // Reporting
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.EXPORT_REPORTS,
    
    // Invoice Management
    PERMISSIONS.CREATE_INVOICES,
    PERMISSIONS.VIEW_INVOICES,
    PERMISSIONS.EDIT_INVOICES,
    
    // Wastage Management
    PERMISSIONS.VIEW_WASTAGE,
    PERMISSIONS.CREATE_WASTAGE,
    PERMISSIONS.EDIT_WASTAGE,
    PERMISSIONS.APPROVE_WASTAGE
  ],
  
  [USER_ROLES.SALES]: [
    // Customer Management
    PERMISSIONS.MANAGE_CUSTOMERS,
    PERMISSIONS.VIEW_CUSTOMERS,
    
    // Inventory (view only)
    PERMISSIONS.VIEW_INVENTORY,
    
    // Sales Management
    PERMISSIONS.CREATE_SALES,
    PERMISSIONS.VIEW_SALES,
    PERMISSIONS.EDIT_SALES,
    
    // Contract Management (view only)
    PERMISSIONS.VIEW_CONTRACTS,
    
    // Basic Financial (view only)
    PERMISSIONS.VIEW_FINANCIALS,
    
    // Basic Reporting
    PERMISSIONS.VIEW_REPORTS,
    
    // Invoice Management
    PERMISSIONS.CREATE_INVOICES,
    PERMISSIONS.VIEW_INVOICES,
    PERMISSIONS.EDIT_INVOICES,
    
    // Wastage Management (view only)
    PERMISSIONS.VIEW_WASTAGE
  ],
  
  [USER_ROLES.PURCHASE]: [
    // Supplier Management
    PERMISSIONS.MANAGE_SUPPLIERS,
    PERMISSIONS.VIEW_SUPPLIERS,
    
    // Vendor Management
    PERMISSIONS.MANAGE_VENDORS,
    PERMISSIONS.VIEW_VENDORS,
    
    // Inventory Management
    PERMISSIONS.MANAGE_INVENTORY,
    PERMISSIONS.VIEW_INVENTORY,
    PERMISSIONS.UPDATE_STOCK,
    
    // Purchase Management
    PERMISSIONS.CREATE_PURCHASE,
    PERMISSIONS.VIEW_PURCHASE,
    PERMISSIONS.EDIT_PURCHASE,
    
    // Purchase Order Management
    PERMISSIONS.CREATE_PURCHASE_ORDER,
    PERMISSIONS.VIEW_PURCHASE_ORDER,
    PERMISSIONS.EDIT_PURCHASE_ORDER,
    
    // Contract Management (view only)
    PERMISSIONS.VIEW_CONTRACTS,
    
    // Basic Financial (view only)
    PERMISSIONS.VIEW_FINANCIALS,
    
    // Basic Reporting
    PERMISSIONS.VIEW_REPORTS,
    
    // Wastage Management
    PERMISSIONS.VIEW_WASTAGE,
    PERMISSIONS.CREATE_WASTAGE,
    PERMISSIONS.EDIT_WASTAGE
  ],
  
  [USER_ROLES.ACCOUNTS]: [
    // View customers/suppliers
    PERMISSIONS.VIEW_CUSTOMERS,
    PERMISSIONS.VIEW_SUPPLIERS,
    
    // View inventory
    PERMISSIONS.VIEW_INVENTORY,
    
    // View sales/purchase
    PERMISSIONS.VIEW_SALES,
    PERMISSIONS.VIEW_PURCHASE,
    
    // Financial Management
    PERMISSIONS.VIEW_FINANCIALS,
    PERMISSIONS.MANAGE_EXPENSES,
    PERMISSIONS.MANAGE_PETTY_CASH,
    PERMISSIONS.VIEW_PROFIT_LOSS,
    
    // Reporting
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.EXPORT_REPORTS,
    
    // Invoice Management
    PERMISSIONS.VIEW_INVOICES,
    PERMISSIONS.EDIT_INVOICES,
    
    // Wastage Management (view only)
    PERMISSIONS.VIEW_WASTAGE
  ]
}

// Note: Business type permissions are now defined per-company in companies.json
// This makes the system flexible and allows each company to have custom modules

export const getRoleDisplayName = (role) => {
  const displayNames = {
    [USER_ROLES.SUPER_ADMIN]: 'Super Admin',
    [USER_ROLES.COMPANY_ADMIN]: 'Company Admin',
    [USER_ROLES.MANAGER]: 'Manager',
    [USER_ROLES.SALES]: 'Sales',
    [USER_ROLES.PURCHASE]: 'Purchase',
    [USER_ROLES.ACCOUNTS]: 'Accounts'
  }
  return displayNames[role] || role
}

export const getRoleColor = (role) => {
  const colors = {
    [USER_ROLES.SUPER_ADMIN]: '#dc2626', // red
    [USER_ROLES.COMPANY_ADMIN]: '#7c3aed', // purple
    [USER_ROLES.MANAGER]: '#059669', // green
    [USER_ROLES.SALES]: '#3b82f6', // blue
    [USER_ROLES.PURCHASE]: '#f59e0b', // amber
    [USER_ROLES.ACCOUNTS]: '#6b7280' // gray
  }
  return colors[role] || '#6b7280'
}