// Role-based Access Control Configuration
export const USER_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  COMPANY_ADMIN: 'COMPANY_ADMIN', 
  MANAGER: 'MANAGER',
  SALES_STAFF: 'SALES_STAFF',
  PURCHASE_STAFF: 'PURCHASE_STAFF',
  ACCOUNTS_STAFF: 'ACCOUNTS_STAFF'
}

export const ROLE_HIERARCHY = {
  [USER_ROLES.SUPER_ADMIN]: 6,
  [USER_ROLES.COMPANY_ADMIN]: 5,
  [USER_ROLES.MANAGER]: 4,
  [USER_ROLES.SALES_STAFF]: 3,
  [USER_ROLES.PURCHASE_STAFF]: 3,
  [USER_ROLES.ACCOUNTS_STAFF]: 3
}

export const PERMISSIONS = {
  // User Management
  MANAGE_USERS: 'MANAGE_USERS',
  VIEW_USERS: 'VIEW_USERS',
  ASSIGN_ROLES: 'ASSIGN_ROLES',
  MANAGE_ROLES: 'MANAGE_ROLES',
  VIEW_ROLES: 'VIEW_ROLES',
  
  // Company Management
  MANAGE_COMPANIES: 'MANAGE_COMPANIES',
  VIEW_COMPANIES: 'VIEW_COMPANIES',
  SWITCH_COMPANIES: 'SWITCH_COMPANIES',
  
  // Customer/Supplier Management
  MANAGE_CUSTOMERS: 'MANAGE_CUSTOMERS',
  VIEW_CUSTOMERS: 'VIEW_CUSTOMERS',
  MANAGE_SUPPLIERS: 'MANAGE_SUPPLIERS',
  VIEW_SUPPLIERS: 'VIEW_SUPPLIERS',
  
  // Inventory Management
  MANAGE_INVENTORY: 'MANAGE_INVENTORY',
  VIEW_INVENTORY: 'VIEW_INVENTORY',
  UPDATE_STOCK: 'UPDATE_STOCK',
  
  // Sales Management
  CREATE_SALES: 'CREATE_SALES',
  VIEW_SALES: 'VIEW_SALES',
  EDIT_SALES: 'EDIT_SALES',
  DELETE_SALES: 'DELETE_SALES',
  APPROVE_SALES: 'APPROVE_SALES',
  
  // Purchase Management
  CREATE_PURCHASE: 'CREATE_PURCHASE',
  VIEW_PURCHASE: 'VIEW_PURCHASE',
  EDIT_PURCHASE: 'EDIT_PURCHASE',
  DELETE_PURCHASE: 'DELETE_PURCHASE',
  APPROVE_PURCHASE: 'APPROVE_PURCHASE',
  
  // Purchase Order Management
  CREATE_PURCHASE_ORDER: 'CREATE_PURCHASE_ORDER',
  VIEW_PURCHASE_ORDER: 'VIEW_PURCHASE_ORDER',
  EDIT_PURCHASE_ORDER: 'EDIT_PURCHASE_ORDER',
  DELETE_PURCHASE_ORDER: 'DELETE_PURCHASE_ORDER',
  APPROVE_PURCHASE_ORDER: 'APPROVE_PURCHASE_ORDER',
  
  // Vendor Management
  MANAGE_VENDORS: 'MANAGE_VENDORS',
  VIEW_VENDORS: 'VIEW_VENDORS',
  
  // Contract Management
  MANAGE_CONTRACTS: 'MANAGE_CONTRACTS',
  VIEW_CONTRACTS: 'VIEW_CONTRACTS',
  APPROVE_CONTRACTS: 'APPROVE_CONTRACTS',
  
  // Financial Management
  VIEW_FINANCIALS: 'VIEW_FINANCIALS',
  MANAGE_EXPENSES: 'MANAGE_EXPENSES',
  APPROVE_EXPENSES: 'APPROVE_EXPENSES',
  MANAGE_PETTY_CASH: 'MANAGE_PETTY_CASH',
  VIEW_PROFIT_LOSS: 'VIEW_PROFIT_LOSS',
  VIEW_EXPENSES: 'VIEW_EXPENSES',
  MANAGE_EXPENSE_CATEGORIES: 'MANAGE_EXPENSE_CATEGORIES',
  VIEW_EXPENSE_CATEGORIES: 'VIEW_EXPENSE_CATEGORIES',
  
  // Reporting
  VIEW_REPORTS: 'VIEW_REPORTS',
  EXPORT_REPORTS: 'EXPORT_REPORTS',
  CREATE_CUSTOM_REPORTS: 'CREATE_CUSTOM_REPORTS',
  
  // Invoice Management
  CREATE_INVOICES: 'CREATE_INVOICES',
  VIEW_INVOICES: 'VIEW_INVOICES',
  EDIT_INVOICES: 'EDIT_INVOICES',
  
  // System Settings
  MANAGE_SETTINGS: 'MANAGE_SETTINGS',
  VIEW_SETTINGS: 'VIEW_SETTINGS',
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',
  MANAGE_BACKUPS: 'MANAGE_BACKUPS',
  VIEW_DASHBOARD: 'VIEW_DASHBOARD',
  
  // Wastage Management
  VIEW_WASTAGE: 'VIEW_WASTAGE',
  CREATE_WASTAGE: 'CREATE_WASTAGE',
  EDIT_WASTAGE: 'EDIT_WASTAGE',
  DELETE_WASTAGE: 'DELETE_WASTAGE',
  APPROVE_WASTAGE: 'APPROVE_WASTAGE',
  
  // Petty Cash Management
  VIEW_PETTY_CASH: 'VIEW_PETTY_CASH',
  MANAGE_PETTY_CASH: 'MANAGE_PETTY_CASH',
  CREATE_EXPENSE: 'CREATE_EXPENSE',
  APPROVE_EXPENSE: 'APPROVE_EXPENSE',
  RELOAD_CARD: 'RELOAD_CARD',
  VIEW_EXPENSE_REPORTS: 'VIEW_EXPENSE_REPORTS',
  
  // Collections Management
  VIEW_COLLECTIONS: 'VIEW_COLLECTIONS',
  CREATE_COLLECTIONS: 'CREATE_COLLECTIONS',
  EDIT_COLLECTIONS: 'EDIT_COLLECTIONS',
  DELETE_COLLECTIONS: 'DELETE_COLLECTIONS',
  APPROVE_COLLECTIONS: 'APPROVE_COLLECTIONS',

  // Project Management
  VIEW_PROJECTS: 'VIEW_PROJECTS',
  MANAGE_PROJECTS: 'MANAGE_PROJECTS',

  // Branch Management
  VIEW_BRANCHES: 'VIEW_BRANCHES',

  // Bank Account Management
  VIEW_BANK_ACCOUNTS: 'VIEW_BANK_ACCOUNTS',
  CREATE_BANK_ACCOUNTS: 'CREATE_BANK_ACCOUNTS',
  EDIT_BANK_ACCOUNTS: 'EDIT_BANK_ACCOUNTS',
  DELETE_BANK_ACCOUNTS: 'DELETE_BANK_ACCOUNTS',

  // Contract Location Management
  VIEW_CONTRACT_LOCATIONS: 'VIEW_CONTRACT_LOCATIONS',
  CREATE_CONTRACT_LOCATIONS: 'CREATE_CONTRACT_LOCATIONS',
  EDIT_CONTRACT_LOCATIONS: 'EDIT_CONTRACT_LOCATIONS',
  MANAGE_CONTRACT_LOCATION_RATES: 'MANAGE_CONTRACT_LOCATION_RATES',
  VIEW_CONTRACT_LOCATION_RATES: 'VIEW_CONTRACT_LOCATION_RATES',

  // Supplier Location Management
  VIEW_SUPPLIER_LOCATIONS: 'VIEW_SUPPLIER_LOCATIONS',
  CREATE_SUPPLIER_LOCATIONS: 'CREATE_SUPPLIER_LOCATIONS',
  EDIT_SUPPLIER_LOCATIONS: 'EDIT_SUPPLIER_LOCATIONS',
  DELETE_SUPPLIER_LOCATIONS: 'DELETE_SUPPLIER_LOCATIONS',

  // Material Composition Management
  VIEW_MATERIAL_COMPOSITIONS: 'VIEW_MATERIAL_COMPOSITIONS',
  CREATE_MATERIAL_COMPOSITIONS: 'CREATE_MATERIAL_COMPOSITIONS',
  EDIT_MATERIAL_COMPOSITIONS: 'EDIT_MATERIAL_COMPOSITIONS',
  DELETE_MATERIAL_COMPOSITIONS: 'DELETE_MATERIAL_COMPOSITIONS',

  // Inventory Batch Management
  VIEW_INVENTORY_BATCHES: 'VIEW_INVENTORY_BATCHES',
  MANAGE_INVENTORY_BATCHES: 'MANAGE_INVENTORY_BATCHES',

  // Supplier Contract Management
  VIEW_SUPPLIER_CONTRACTS: 'VIEW_SUPPLIER_CONTRACTS',

  // Customer & Supplier Type Management
  VIEW_CUSTOMER_TYPES: 'VIEW_CUSTOMER_TYPES',
  VIEW_SUPPLIER_TYPES: 'VIEW_SUPPLIER_TYPES',

  // Purchase Order Expense Management (Ownership-Scoped)
  VIEW_PO_EXPENSES_ALL: 'VIEW_PO_EXPENSES_ALL',
  VIEW_PO_EXPENSES_OWN: 'VIEW_PO_EXPENSES_OWN',
  CREATE_PO_EXPENSES: 'CREATE_PO_EXPENSES',
  EDIT_PO_EXPENSES_ALL: 'EDIT_PO_EXPENSES_ALL',
  EDIT_PO_EXPENSES_OWN: 'EDIT_PO_EXPENSES_OWN',
  DELETE_PO_EXPENSES_ALL: 'DELETE_PO_EXPENSES_ALL',
  DELETE_PO_EXPENSES_OWN: 'DELETE_PO_EXPENSES_OWN',

  // Purchase Order Amendment Management (Ownership-Scoped)
  VIEW_AMENDMENTS_ALL: 'VIEW_AMENDMENTS_ALL',
  VIEW_AMENDMENTS_OWN: 'VIEW_AMENDMENTS_OWN',
  CREATE_AMENDMENTS: 'CREATE_AMENDMENTS',
  EDIT_AMENDMENTS_ALL: 'EDIT_AMENDMENTS_ALL',
  EDIT_AMENDMENTS_OWN: 'EDIT_AMENDMENTS_OWN',
  APPROVE_AMENDMENTS: 'APPROVE_AMENDMENTS',

  // Macro-level MANAGE_* permissions
  MANAGE_SALES: 'MANAGE_SALES',
  MANAGE_PURCHASE: 'MANAGE_PURCHASE',
  MANAGE_WASTAGE: 'MANAGE_WASTAGE',
  MANAGE_COLLECTIONS: 'MANAGE_COLLECTIONS',
  MANAGE_FINANCIALS: 'MANAGE_FINANCIALS',
  MANAGE_INVOICES: 'MANAGE_INVOICES',
  MANAGE_BANKING: 'MANAGE_BANKING',
  MANAGE_MATERIALS: 'MANAGE_MATERIALS',

  // Employee Management
  VIEW_EMPLOYEES: 'VIEW_EMPLOYEES',
  MANAGE_EMPLOYEES: 'MANAGE_EMPLOYEES',
  DELETE_EMPLOYEES: 'DELETE_EMPLOYEES',

  // Vehicle Management
  VIEW_VEHICLES: 'VIEW_VEHICLES',
  MANAGE_VEHICLES: 'MANAGE_VEHICLES',
  MANAGE_VEHICLE_TYPES: 'MANAGE_VEHICLE_TYPES',

  // Tank Log Management
  VIEW_TANK_LOGS: 'VIEW_TANK_LOGS',
  MANAGE_TANK_LOGS: 'MANAGE_TANK_LOGS',

  // Vehicle Expense Sheet Management
  VIEW_EXPENSE_SHEETS: 'VIEW_EXPENSE_SHEETS',
  MANAGE_EXPENSE_SHEETS: 'MANAGE_EXPENSE_SHEETS',
  APPROVE_EXPENSE_SHEETS: 'APPROVE_EXPENSE_SHEETS'
}

export const PARENT_PERMISSIONS = {
  MANAGE_USERS: ['VIEW_USERS', 'CREATE_USERS', 'EDIT_USERS', 'DELETE_USERS', 'ASSIGN_ROLES'],
  MANAGE_ROLES: ['VIEW_ROLES', 'CREATE_ROLES', 'EDIT_ROLES', 'DELETE_ROLES', 'MANAGE_ROLE_PERMISSIONS'],
  MANAGE_COMPANIES: ['VIEW_COMPANIES', 'CREATE_COMPANIES', 'EDIT_COMPANIES', 'DELETE_COMPANIES', 'SWITCH_COMPANIES'],
  MANAGE_SETTINGS: ['VIEW_SETTINGS', 'EDIT_SETTINGS', 'VIEW_BRANCHES', 'MANAGE_BRANCHES', 'MANAGE_EXPENSE_CATEGORIES', 'VIEW_EXPENSE_CATEGORIES'],
  MANAGE_BANKING: ['VIEW_BANK_ACCOUNTS', 'CREATE_BANK_ACCOUNTS', 'EDIT_BANK_ACCOUNTS', 'DELETE_BANK_ACCOUNTS', 'VIEW_BANKING'],
  MANAGE_CUSTOMERS: ['VIEW_CUSTOMERS', 'CREATE_CUSTOMERS', 'EDIT_CUSTOMERS', 'DELETE_CUSTOMERS', 'VIEW_CUSTOMER_TYPES'],
  MANAGE_SUPPLIERS: ['VIEW_SUPPLIERS', 'CREATE_SUPPLIERS', 'EDIT_SUPPLIERS', 'DELETE_SUPPLIERS', 'VIEW_SUPPLIER_LOCATIONS', 'CREATE_SUPPLIER_LOCATIONS', 'EDIT_SUPPLIER_LOCATIONS', 'DELETE_SUPPLIER_LOCATIONS', 'VIEW_SUPPLIER_CONTRACTS', 'VIEW_SUPPLIER_TYPES'],
  MANAGE_VENDORS: ['VIEW_VENDORS', 'CREATE_VENDORS', 'EDIT_VENDORS', 'DELETE_VENDORS'],
  MANAGE_MATERIALS: ['VIEW_MATERIALS', 'CREATE_MATERIALS', 'EDIT_MATERIALS', 'DELETE_MATERIALS', 'VIEW_MATERIAL_COMPOSITIONS', 'CREATE_MATERIAL_COMPOSITIONS', 'EDIT_MATERIAL_COMPOSITIONS', 'DELETE_MATERIAL_COMPOSITIONS'],
  MANAGE_INVENTORY: ['VIEW_INVENTORY', 'UPDATE_STOCK', 'VIEW_INVENTORY_BATCHES', 'MANAGE_INVENTORY_BATCHES'],
  MANAGE_SALES: ['VIEW_SALES', 'CREATE_SALES', 'EDIT_SALES', 'DELETE_SALES', 'APPROVE_SALES'],
  MANAGE_PURCHASE: ['VIEW_PURCHASE', 'CREATE_PURCHASE', 'EDIT_PURCHASE', 'DELETE_PURCHASE', 'APPROVE_PURCHASE',
    'VIEW_PURCHASE_ORDER', 'CREATE_PURCHASE_ORDER', 'EDIT_PURCHASE_ORDER', 'DELETE_PURCHASE_ORDER', 'APPROVE_PURCHASE_ORDER',
    'VIEW_PO_EXPENSES_ALL', 'VIEW_PO_EXPENSES_OWN', 'CREATE_PO_EXPENSES', 'EDIT_PO_EXPENSES_ALL', 'EDIT_PO_EXPENSES_OWN', 'DELETE_PO_EXPENSES_ALL', 'DELETE_PO_EXPENSES_OWN',
    'VIEW_AMENDMENTS_ALL', 'VIEW_AMENDMENTS_OWN', 'CREATE_AMENDMENTS', 'EDIT_AMENDMENTS_ALL', 'EDIT_AMENDMENTS_OWN', 'APPROVE_AMENDMENTS'],
  MANAGE_CONTRACTS: ['VIEW_CONTRACTS', 'CREATE_CONTRACTS', 'EDIT_CONTRACTS', 'DELETE_CONTRACTS', 'APPROVE_CONTRACTS',
    'VIEW_CONTRACT_LOCATIONS', 'CREATE_CONTRACT_LOCATIONS', 'EDIT_CONTRACT_LOCATIONS', 'MANAGE_CONTRACT_LOCATION_RATES', 'VIEW_CONTRACT_LOCATION_RATES'],
  MANAGE_COLLECTIONS: ['VIEW_COLLECTIONS', 'CREATE_COLLECTIONS', 'EDIT_COLLECTIONS', 'DELETE_COLLECTIONS', 'APPROVE_COLLECTIONS'],
  MANAGE_WASTAGE: ['VIEW_WASTAGE', 'CREATE_WASTAGE', 'EDIT_WASTAGE', 'DELETE_WASTAGE', 'APPROVE_WASTAGE'],
  MANAGE_FINANCIALS: ['VIEW_FINANCIALS', 'VIEW_PROFIT_LOSS', 'MANAGE_EXPENSES', 'APPROVE_EXPENSES', 'VIEW_EXPENSES', 'MANAGE_EXPENSE_CATEGORIES', 'VIEW_EXPENSE_CATEGORIES'],
  MANAGE_INVOICES: ['VIEW_INVOICES', 'CREATE_INVOICES', 'EDIT_INVOICES'],
  MANAGE_PETTY_CASH: ['VIEW_PETTY_CASH', 'CREATE_EXPENSE', 'APPROVE_EXPENSE', 'RELOAD_CARD', 'VIEW_EXPENSE_REPORTS'],
  MANAGE_PROJECTS: ['VIEW_PROJECTS'],
  MANAGE_EMPLOYEES: ['VIEW_EMPLOYEES', 'CREATE_EMPLOYEES', 'EDIT_EMPLOYEES'],
  MANAGE_VEHICLES: ['VIEW_VEHICLES'],
  MANAGE_VEHICLE_TYPES: ['VIEW_VEHICLES'],
  MANAGE_TANK_LOGS: ['VIEW_TANK_LOGS'],
  MANAGE_EXPENSE_SHEETS: ['VIEW_EXPENSE_SHEETS'],
  APPROVE_EXPENSE_SHEETS: ['VIEW_EXPENSE_SHEETS'],
}

export const ROLE_PERMISSIONS = {
  [USER_ROLES.SUPER_ADMIN]: [
    // All permissions
    ...Object.values(PERMISSIONS)
  ],
  
  [USER_ROLES.COMPANY_ADMIN]: [
    // User & Role Management
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_ROLES,
    PERMISSIONS.VIEW_ROLES,

    // Company & Settings (no MANAGE_COMPANIES / SWITCH_COMPANIES / MANAGE_BACKUPS — super admin only)
    PERMISSIONS.VIEW_COMPANIES,
    PERMISSIONS.MANAGE_SETTINGS,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.VIEW_DASHBOARD,

    // Data Management
    PERMISSIONS.MANAGE_CUSTOMERS,
    PERMISSIONS.MANAGE_SUPPLIERS,
    PERMISSIONS.MANAGE_VENDORS,
    PERMISSIONS.MANAGE_MATERIALS,
    PERMISSIONS.MANAGE_INVENTORY,

    // Operations
    PERMISSIONS.MANAGE_SALES,
    PERMISSIONS.MANAGE_PURCHASE,
    PERMISSIONS.MANAGE_CONTRACTS,
    PERMISSIONS.MANAGE_COLLECTIONS,
    PERMISSIONS.MANAGE_WASTAGE,

    // Finance & Reporting
    PERMISSIONS.MANAGE_FINANCIALS,
    PERMISSIONS.MANAGE_INVOICES,
    PERMISSIONS.MANAGE_PETTY_CASH,
    PERMISSIONS.MANAGE_BANKING,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.EXPORT_REPORTS,
    PERMISSIONS.CREATE_CUSTOM_REPORTS,

    // HR & Operations
    PERMISSIONS.MANAGE_PROJECTS,
    PERMISSIONS.MANAGE_EMPLOYEES,
    PERMISSIONS.DELETE_EMPLOYEES,
    PERMISSIONS.MANAGE_VEHICLES,
    PERMISSIONS.MANAGE_VEHICLE_TYPES,
    PERMISSIONS.MANAGE_TANK_LOGS,
    PERMISSIONS.MANAGE_EXPENSE_SHEETS,
    PERMISSIONS.APPROVE_EXPENSE_SHEETS,
  ],

  [USER_ROLES.MANAGER]: [
    // User Management (view only)
    PERMISSIONS.VIEW_USERS,

    // Customer/Supplier/Vendor Management
    PERMISSIONS.MANAGE_CUSTOMERS,
    PERMISSIONS.MANAGE_SUPPLIERS,
    PERMISSIONS.MANAGE_VENDORS,
    PERMISSIONS.MANAGE_MATERIALS,
    PERMISSIONS.MANAGE_INVENTORY,

    // Operations
    PERMISSIONS.MANAGE_SALES,
    PERMISSIONS.MANAGE_PURCHASE,
    PERMISSIONS.MANAGE_CONTRACTS,
    PERMISSIONS.MANAGE_COLLECTIONS,
    PERMISSIONS.MANAGE_WASTAGE,

    // Finance & Reporting
    PERMISSIONS.MANAGE_FINANCIALS,
    PERMISSIONS.MANAGE_INVOICES,
    PERMISSIONS.MANAGE_PETTY_CASH,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.EXPORT_REPORTS,

    // HR & Operations
    PERMISSIONS.MANAGE_PROJECTS,
    PERMISSIONS.MANAGE_EMPLOYEES,
    PERMISSIONS.MANAGE_VEHICLES,
    PERMISSIONS.MANAGE_TANK_LOGS,
    PERMISSIONS.MANAGE_EXPENSE_SHEETS,
    PERMISSIONS.APPROVE_EXPENSE_SHEETS,
  ],

  [USER_ROLES.SALES_STAFF]: [
    // Customer Management
    PERMISSIONS.MANAGE_CUSTOMERS,
    PERMISSIONS.VIEW_CUSTOMERS,
    
    // Supplier Management (view only)
    PERMISSIONS.VIEW_SUPPLIERS,
    
    // Inventory (view only)
    PERMISSIONS.VIEW_INVENTORY,
    
    // Sales Management
    PERMISSIONS.CREATE_SALES,
    PERMISSIONS.VIEW_SALES,
    PERMISSIONS.EDIT_SALES,
    
    // Contract Management (view only)
    PERMISSIONS.VIEW_CONTRACTS,
    
    // Basic Financial (view only)
    PERMISSIONS.VIEW_FINANCIALS,
    
    // Basic Reporting
    PERMISSIONS.VIEW_REPORTS,
    
    // Invoice Management
    PERMISSIONS.CREATE_INVOICES,
    PERMISSIONS.VIEW_INVOICES,
    PERMISSIONS.EDIT_INVOICES,
    
    // Wastage Management (view only)
    PERMISSIONS.VIEW_WASTAGE,
    
    // Petty Cash Management (view only)
    PERMISSIONS.VIEW_PETTY_CASH,

    // Project Management (view only)
    PERMISSIONS.VIEW_PROJECTS,

    // Employee Management (view only)
    PERMISSIONS.VIEW_EMPLOYEES,

    // Vehicle Management (view only)
    PERMISSIONS.VIEW_VEHICLES,

    // Tank Log (view only)
    PERMISSIONS.VIEW_TANK_LOGS,

    // Expense Sheets (view only)
    PERMISSIONS.VIEW_EXPENSE_SHEETS
  ],

  [USER_ROLES.PURCHASE_STAFF]: [
    // Supplier Management
    PERMISSIONS.MANAGE_SUPPLIERS,
    PERMISSIONS.VIEW_SUPPLIERS,
    
    // Vendor Management
    PERMISSIONS.MANAGE_VENDORS,
    PERMISSIONS.VIEW_VENDORS,
    
    // Inventory Management
    PERMISSIONS.MANAGE_INVENTORY,
    PERMISSIONS.VIEW_INVENTORY,
    PERMISSIONS.UPDATE_STOCK,
    
    // Purchase Management
    PERMISSIONS.CREATE_PURCHASE,
    PERMISSIONS.VIEW_PURCHASE,
    PERMISSIONS.EDIT_PURCHASE,
    
    // Purchase Order Management
    PERMISSIONS.CREATE_PURCHASE_ORDER,
    PERMISSIONS.VIEW_PURCHASE_ORDER,
    PERMISSIONS.EDIT_PURCHASE_ORDER,
    
    // Contract Management (view only)
    PERMISSIONS.VIEW_CONTRACTS,
    
    // Basic Financial (view only)
    PERMISSIONS.VIEW_FINANCIALS,
    
    // Basic Reporting
    PERMISSIONS.VIEW_REPORTS,
    
    // Wastage Management
    PERMISSIONS.VIEW_WASTAGE,
    PERMISSIONS.CREATE_WASTAGE,
    PERMISSIONS.EDIT_WASTAGE,
    
    // Petty Cash Management
    PERMISSIONS.VIEW_PETTY_CASH,
    PERMISSIONS.CREATE_EXPENSE,

    // Project Management (view only)
    PERMISSIONS.VIEW_PROJECTS,

    // Employee Management (view only)
    PERMISSIONS.VIEW_EMPLOYEES,

    // Vehicle Management (view only)
    PERMISSIONS.VIEW_VEHICLES,

    // Tank Log (view only)
    PERMISSIONS.VIEW_TANK_LOGS,

    // Expense Sheets (create/submit)
    PERMISSIONS.VIEW_EXPENSE_SHEETS,
    PERMISSIONS.MANAGE_EXPENSE_SHEETS
  ],

  [USER_ROLES.ACCOUNTS_STAFF]: [
    // View customers/suppliers
    PERMISSIONS.VIEW_CUSTOMERS,
    PERMISSIONS.VIEW_SUPPLIERS,
    
    // View inventory
    PERMISSIONS.VIEW_INVENTORY,
    
    // View sales/purchase
    PERMISSIONS.VIEW_SALES,
    PERMISSIONS.VIEW_PURCHASE,
    
    // Financial Management
    PERMISSIONS.VIEW_FINANCIALS,
    PERMISSIONS.MANAGE_EXPENSES,
    PERMISSIONS.MANAGE_PETTY_CASH,
    PERMISSIONS.VIEW_PROFIT_LOSS,
    
    // Reporting
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.EXPORT_REPORTS,
    
    // Invoice Management
    PERMISSIONS.VIEW_INVOICES,
    PERMISSIONS.EDIT_INVOICES,
    
    // Wastage Management (view only)
    PERMISSIONS.VIEW_WASTAGE,
    
    // Petty Cash Management
    PERMISSIONS.VIEW_PETTY_CASH,
    PERMISSIONS.VIEW_EXPENSE_REPORTS,

    // Project Management (view only)
    PERMISSIONS.VIEW_PROJECTS,

    // Employee Management (view only)
    PERMISSIONS.VIEW_EMPLOYEES,

    // Vehicle Management (view only)
    PERMISSIONS.VIEW_VEHICLES,

    // Tank Log (view only)
    PERMISSIONS.VIEW_TANK_LOGS,

    // Expense Sheets (view only)
    PERMISSIONS.VIEW_EXPENSE_SHEETS
  ]
}

// Note: Business type permissions are now defined per-company in companies.json
// This makes the system flexible and allows each company to have custom modules

export const getRoleDisplayName = (role) => {
  const displayNames = {
    [USER_ROLES.SUPER_ADMIN]: 'Super Admin',
    [USER_ROLES.COMPANY_ADMIN]: 'Company Admin',
    [USER_ROLES.MANAGER]: 'Manager',
    [USER_ROLES.SALES_STAFF]: 'Sales Staff',
    [USER_ROLES.PURCHASE_STAFF]: 'Purchase Staff',
    [USER_ROLES.ACCOUNTS_STAFF]: 'Accounts Staff'
  }
  return displayNames[role] || role
}

export const getRoleColor = (role) => {
  const colors = {
    [USER_ROLES.SUPER_ADMIN]: '#dc2626', // red
    [USER_ROLES.COMPANY_ADMIN]: '#7c3aed', // purple
    [USER_ROLES.MANAGER]: '#059669', // green
    [USER_ROLES.SALES_STAFF]: '#3b82f6', // blue
    [USER_ROLES.PURCHASE_STAFF]: '#f59e0b', // amber
    [USER_ROLES.ACCOUNTS_STAFF]: '#6b7280' // gray
  }
  return colors[role] || '#6b7280'
}