import React, { useState, useEffect, useMemo } from 'react'
import Modal from '../ui/Modal'
import { FileText, CheckSquare, Square, AlertTriangle, Receipt, Calculator, Link2 } from 'lucide-react'
import './VendorBillModal.css'

/**
 * VendorBillModal Component
 *
 * Modal for creating or editing vendor bills that link to company bills.
 * In the new workflow:
 * - Vendor bills link to Company Bills (not directly to POs)
 * - Company bills must be "sent" to be linkable
 * - Each company bill is associated with exactly 1 PO
 *
 * @param {boolean} isOpen - Modal visibility
 * @param {Function} onClose - Close handler
 * @param {Function} onSave - Save handler (receives vendor bill data)
 * @param {Function} onUpdate - Update handler for edit mode (receives id and data)
 * @param {Array} companyBills - Available company bills to link (with PO details)
 * @param {Array} purchaseOrders - Purchase orders for legacy PO reference lookup
 * @param {Array} suppliers - Available suppliers for dropdown
 * @param {Array} existingBills - Existing vendor bills to check for already-linked company bills
 * @param {Object} editingBill - Bill to edit (null for create mode)
 * @param {Function} formatCurrency - Currency formatting function
 */
const VendorBillModal = ({
  isOpen,
  onClose,
  onSave,
  onUpdate,
  companyBills = [],
  purchaseOrders = [],
  suppliers = [],
  existingBills = [],
  editingBill = null,
  formatCurrency
}) => {
  // Determine if we're in edit mode
  const isEditMode = !!editingBill

  // Form state (invoiceNumber is auto-generated by backend)
  const [formData, setFormData] = useState({
    invoiceDate: new Date().toISOString().split('T')[0],
    dueDate: '',
    supplierId: '',
    invoiceAmount: '',
    notes: ''
  })

  // Selected company bills
  const [selectedBills, setSelectedBills] = useState(new Set())
  const [submitting, setSubmitting] = useState(false)
  const [error, setError] = useState('')

  // Create a lookup for PO details by ID
  const poLookup = useMemo(() => {
    const lookup = {}
    purchaseOrders.forEach(po => {
      lookup[po.id] = po
    })
    return lookup
  }, [purchaseOrders])

  // Reset form when modal opens or populate with editing data
  useEffect(() => {
    if (isOpen) {
      if (editingBill) {
        // Edit mode - populate form with existing bill data
        setFormData({
          invoiceDate: editingBill.invoice_date
            ? new Date(editingBill.invoice_date).toISOString().split('T')[0]
            : new Date().toISOString().split('T')[0],
          dueDate: editingBill.due_date
            ? new Date(editingBill.due_date).toISOString().split('T')[0]
            : '',
          supplierId: editingBill.supplier_id?.toString() || '',
          invoiceAmount: editingBill.invoice_amount?.toString() || '',
          notes: editingBill.notes || ''
        })
        // Pre-select linked company bills (new workflow) or fall back to PO-based lookup (legacy)
        if (editingBill.covers_company_bills && editingBill.covers_company_bills.length > 0) {
          setSelectedBills(new Set(editingBill.covers_company_bills))
        } else if (editingBill.covers_purchase_orders && editingBill.covers_purchase_orders.length > 0) {
          // Legacy: Find company bills for these PO IDs
          const linkedBillIds = companyBills
            .filter(cb => editingBill.covers_purchase_orders.includes(cb.purchase_order_id))
            .map(cb => cb.id)
          setSelectedBills(new Set(linkedBillIds))
        } else {
          setSelectedBills(new Set())
        }
      } else {
        // Create mode - reset to defaults
        setFormData({
          invoiceDate: new Date().toISOString().split('T')[0],
          dueDate: '',
          supplierId: '',
          invoiceAmount: '',
          notes: ''
        })
        setSelectedBills(new Set())
      }
      setError('')
    }
  }, [isOpen, editingBill, companyBills])

  // Get company bill IDs that are already linked to vendor bills (excluding current bill if editing)
  const linkedCompanyBillIds = useMemo(() => {
    const ids = new Set()
    existingBills
      .filter(b => {
        // Only vendor bills with linked company bills
        if (b.bill_type !== 'vendor') return false
        // In edit mode, exclude the current bill so its linked bills appear available
        if (isEditMode && b.id === editingBill.id) return false
        return true
      })
      .forEach(b => {
        // Check covers_company_bills (new workflow)
        if (b.covers_company_bills && Array.isArray(b.covers_company_bills)) {
          b.covers_company_bills.forEach(cbId => ids.add(cbId))
        }
        // Also check covers_purchase_orders for legacy data
        // Find company bills for those POs and mark them as linked
        if (b.covers_purchase_orders && Array.isArray(b.covers_purchase_orders)) {
          companyBills
            .filter(cb => b.covers_purchase_orders.includes(cb.purchase_order_id))
            .forEach(cb => ids.add(cb.id))
        }
      })
    return ids
  }, [existingBills, companyBills, isEditMode, editingBill])

  // Filter company bills: show "sent" bills that aren't linked to other vendor bills
  // In edit mode, always include bills currently linked to this bill
  const availableCompanyBills = useMemo(() => {
    if (!isOpen) return []

    // Get currently linked bill IDs for this bill (in edit mode)
    const currentlyLinkedBillIds = isEditMode && editingBill
      ? new Set(
          editingBill.covers_company_bills ||
          companyBills
            .filter(cb => editingBill.covers_purchase_orders?.includes(cb.purchase_order_id))
            .map(cb => cb.id)
        )
      : new Set()

    return companyBills.filter(cb => {
      // Always include bills currently linked to this vendor bill
      if (currentlyLinkedBillIds.has(cb.id)) return true

      // Must be "sent" status (not draft) - or if bill_status not set, allow all for backward compat
      const isSent = !cb.bill_status || cb.bill_status === 'sent'
      // Not already linked to another vendor bill
      const notLinked = !linkedCompanyBillIds.has(cb.id)

      return isSent && notLinked
    })
  }, [companyBills, linkedCompanyBillIds, isOpen, isEditMode, editingBill])

  // Group available company bills by supplier
  const billsBySupplier = useMemo(() => {
    const grouped = {}
    availableCompanyBills.forEach(cb => {
      const supplierId = cb.supplier_id || 'unknown'
      if (!grouped[supplierId]) {
        grouped[supplierId] = {
          supplierId,
          supplierName: cb.supplier_name || 'Unknown Supplier',
          bills: []
        }
      }
      grouped[supplierId].bills.push(cb)
    })
    return Object.values(grouped)
  }, [availableCompanyBills])

  // Filter company bills when supplier is selected
  const filteredBills = useMemo(() => {
    if (!formData.supplierId) return availableCompanyBills
    return availableCompanyBills.filter(cb =>
      cb.supplier_id === parseInt(formData.supplierId)
    )
  }, [availableCompanyBills, formData.supplierId])

  // Calculate total of selected company bills
  const selectedTotal = useMemo(() => {
    return filteredBills
      .filter(cb => selectedBills.has(cb.id))
      .reduce((sum, cb) => sum + (parseFloat(cb.invoice_amount) || 0), 0)
  }, [filteredBills, selectedBills])

  // Handle supplier change - clear selected bills for other suppliers
  const handleSupplierChange = (supplierId) => {
    setFormData(prev => ({ ...prev, supplierId }))
    // Clear selections when supplier changes
    setSelectedBills(new Set())
  }

  // Toggle company bill selection
  const toggleBill = (billId) => {
    setSelectedBills(prev => {
      const next = new Set(prev)
      if (next.has(billId)) {
        next.delete(billId)
      } else {
        next.add(billId)
      }
      return next
    })
  }

  // Select all bills for current supplier
  const selectAllBills = () => {
    setSelectedBills(new Set(filteredBills.map(cb => cb.id)))
  }

  // Clear all selections
  const clearSelections = () => {
    setSelectedBills(new Set())
  }

  // Get PO reference for a company bill
  const getPOReference = (companyBill) => {
    if (companyBill.order_number) return companyBill.order_number
    const po = poLookup[companyBill.purchase_order_id]
    return po?.orderNumber || po?.order_number || `PO-${companyBill.purchase_order_id}`
  }

  // Handle form submission (create or update)
  const handleSubmit = async (e) => {
    e.preventDefault()
    setError('')

    // Validation
    if (!formData.supplierId) {
      setError('Please select a supplier')
      return
    }
    if (selectedBills.size === 0) {
      setError('Please select at least one company bill')
      return
    }
    if (!formData.invoiceAmount || parseFloat(formData.invoiceAmount) <= 0) {
      setError('Please enter a valid invoice amount')
      return
    }

    setSubmitting(true)

    try {
      if (isEditMode) {
        // Update existing vendor bill - use new coversCompanyBills field
        const updateData = {
          invoiceDate: formData.invoiceDate,
          dueDate: formData.dueDate || null,
          invoiceAmount: parseFloat(formData.invoiceAmount),
          notes: formData.notes.trim(),
          coversCompanyBills: Array.from(selectedBills)
        }
        await onUpdate(editingBill.id, updateData)
      } else {
        // Create new vendor bill with coversCompanyBills
        const vendorBillData = {
          // invoiceNumber is auto-generated by backend (format: VB-YYYY-NNNNN)
          invoiceDate: formData.invoiceDate,
          dueDate: formData.dueDate || null,
          supplierId: parseInt(formData.supplierId),
          invoiceAmount: parseFloat(formData.invoiceAmount),
          notes: formData.notes.trim(),
          coversCompanyBills: Array.from(selectedBills),
          billType: 'vendor'
        }
        await onSave(vendorBillData)
      }
    } catch (err) {
      setError(err.message || `Failed to ${isEditMode ? 'update' : 'create'} vendor bill`)
    } finally {
      setSubmitting(false)
    }
  }

  // Get selected supplier name
  const selectedSupplier = suppliers.find(s => s.id === parseInt(formData.supplierId))

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title={isEditMode ? `Edit Vendor Bill - ${editingBill?.invoice_number}` : 'Create Vendor Bill'}
      size="lg"
    >
      <form onSubmit={handleSubmit} className="vendor-bill-form">
        {error && (
          <div className="form-error">
            <AlertTriangle size={16} />
            <span>{error}</span>
          </div>
        )}

        {/* Bill Details Section */}
        <div className="form-section">
          <h4 className="section-title">
            <Receipt size={16} />
            Bill Details
          </h4>

          <div className="form-grid">
            <div className="form-group">
              <label>Invoice Number</label>
              {isEditMode ? (
                <div className="readonly-field">
                  <span className="invoice-number-display">{editingBill?.invoice_number}</span>
                </div>
              ) : (
                <div className="auto-generated-field">
                  <span className="auto-badge">Auto-generated</span>
                  <span className="auto-hint">Format: VB-{new Date().getFullYear()}-XXXXX</span>
                </div>
              )}
            </div>

            <div className="form-group">
              <label htmlFor="supplierId">Supplier *</label>
              <select
                id="supplierId"
                value={formData.supplierId}
                onChange={(e) => handleSupplierChange(e.target.value)}
                className="form-select"
                required
                disabled={isEditMode}
              >
                <option value="">Select Supplier</option>
                {suppliers.map(supplier => (
                  <option key={supplier.id} value={supplier.id}>
                    {supplier.name}
                  </option>
                ))}
              </select>
              {isEditMode && (
                <span className="field-hint">Supplier cannot be changed when editing</span>
              )}
            </div>

            <div className="form-group">
              <label htmlFor="invoiceDate">Invoice Date *</label>
              <input
                type="date"
                id="invoiceDate"
                value={formData.invoiceDate}
                onChange={(e) => setFormData(prev => ({ ...prev, invoiceDate: e.target.value }))}
                className="form-input"
                required
              />
            </div>

            <div className="form-group">
              <label htmlFor="dueDate">Due Date</label>
              <input
                type="date"
                id="dueDate"
                value={formData.dueDate}
                onChange={(e) => setFormData(prev => ({ ...prev, dueDate: e.target.value }))}
                className="form-input"
              />
            </div>

            <div className="form-group">
              <label htmlFor="invoiceAmount">Invoice Amount *</label>
              <input
                type="number"
                id="invoiceAmount"
                value={formData.invoiceAmount}
                onChange={(e) => setFormData(prev => ({ ...prev, invoiceAmount: e.target.value }))}
                placeholder="0.000"
                step="0.001"
                min="0"
                className="form-input"
                required
              />
            </div>

            <div className="form-group">
              <label>Company Bills Total (Selected)</label>
              <div className="calculated-total">
                {formatCurrency(selectedTotal)}
              </div>
            </div>
          </div>

          <div className="form-group full-width">
            <label htmlFor="notes">Notes</label>
            <textarea
              id="notes"
              value={formData.notes}
              onChange={(e) => setFormData(prev => ({ ...prev, notes: e.target.value }))}
              placeholder="Optional notes about this vendor bill..."
              rows={2}
              className="form-textarea"
            />
          </div>
        </div>

        {/* Company Bills Section */}
        <div className="form-section">
          <h4 className="section-title">
            <Link2 size={16} />
            Link Company Bills
            {formData.supplierId && (
              <span className="po-count">
                {selectedBills.size} of {filteredBills.length} selected
              </span>
            )}
          </h4>

          {!formData.supplierId ? (
            <div className="po-placeholder">
              <FileText size={32} />
              <p>Select a supplier to see available company bills</p>
            </div>
          ) : filteredBills.length === 0 ? (
            <div className="po-placeholder warning">
              <AlertTriangle size={32} />
              <p>No eligible company bills for {selectedSupplier?.name}</p>
              <span className="hint">Only "sent" company bills not linked to other vendor bills are shown</span>
            </div>
          ) : (
            <>
              <div className="po-actions">
                <button
                  type="button"
                  className="btn btn-outline btn-sm"
                  onClick={selectAllBills}
                >
                  Select All
                </button>
                <button
                  type="button"
                  className="btn btn-outline btn-sm"
                  onClick={clearSelections}
                >
                  Clear
                </button>
              </div>

              <div className="po-list">
                {filteredBills.map(cb => {
                  const isSelected = selectedBills.has(cb.id)
                  const isCurrentlyLinked = isEditMode && (
                    editingBill?.covers_company_bills?.includes(cb.id) ||
                    editingBill?.covers_purchase_orders?.includes(cb.purchase_order_id)
                  )
                  const billStatus = cb.bill_status || 'sent'
                  return (
                    <div
                      key={cb.id}
                      className={`po-item ${isSelected ? 'selected' : ''} ${isCurrentlyLinked ? 'currently-linked' : ''}`}
                      onClick={() => toggleBill(cb.id)}
                    >
                      <div className="po-checkbox">
                        {isSelected ? (
                          <CheckSquare size={20} className="checked" />
                        ) : (
                          <Square size={20} />
                        )}
                      </div>
                      <div className="po-details">
                        <div className="po-header">
                          <span className="po-number">{cb.invoice_number}</span>
                          <span className={`bill-status-badge ${billStatus}`}>
                            {billStatus}
                          </span>
                          {isCurrentlyLinked && (
                            <span className="linked-badge">Linked</span>
                          )}
                        </div>
                        <div className="po-info">
                          <span className="po-ref">PO: {getPOReference(cb)}</span>
                          <span className="po-date">{new Date(cb.invoice_date).toLocaleDateString()}</span>
                        </div>
                      </div>
                      <div className="po-amount">
                        {formatCurrency(cb.invoice_amount)}
                      </div>
                    </div>
                  )
                })}
              </div>

              {/* Amount Comparison */}
              {selectedBills.size > 0 && formData.invoiceAmount && (
                <div className="amount-comparison">
                  <Calculator size={16} />
                  <div className="comparison-details">
                    <span>Vendor Bill: {formatCurrency(parseFloat(formData.invoiceAmount))}</span>
                    <span>Company Bills Total: {formatCurrency(selectedTotal)}</span>
                    {Math.abs(parseFloat(formData.invoiceAmount) - selectedTotal) >= 0.01 && (
                      <span className={parseFloat(formData.invoiceAmount) > selectedTotal ? 'diff-positive' : 'diff-negative'}>
                        Difference: {formatCurrency(Math.abs(parseFloat(formData.invoiceAmount) - selectedTotal))}
                      </span>
                    )}
                  </div>
                </div>
              )}
            </>
          )}
        </div>

        {/* Form Actions */}
        <div className="form-actions">
          <button
            type="button"
            className="btn btn-outline"
            onClick={onClose}
            disabled={submitting}
          >
            Cancel
          </button>
          <button
            type="submit"
            className="btn btn-primary"
            disabled={submitting || selectedBills.size === 0}
          >
            {submitting
              ? (isEditMode ? 'Updating...' : 'Creating...')
              : (isEditMode ? 'Update Vendor Bill' : 'Create Vendor Bill')
            }
          </button>
        </div>
      </form>
    </Modal>
  )
}

export default VendorBillModal
