import React, { useState, useEffect, useMemo } from 'react'
import Modal from '../ui/Modal'
import DateInput from '../ui/DateInput'
import { useSystemSettings } from '../../context/SystemSettingsContext'
import { FileText, CheckSquare, Square, AlertTriangle, Receipt, Calculator, Link2 } from 'lucide-react'
// CSS moved to global index.css Tailwind

/**
 * VendorBillModal Component
 *
 * Modal for creating or editing vendor bills that link to company bills.
 * In the new workflow:
 * - Vendor bills link to Company Bills (not directly to POs)
 * - Company bills must be "sent" to be linkable
 * - Each company bill is associated with exactly 1 PO
 *
 * @param {boolean} isOpen - Modal visibility
 * @param {Function} onClose - Close handler
 * @param {Function} onSave - Save handler (receives vendor bill data)
 * @param {Function} onUpdate - Update handler for edit mode (receives id and data)
 * @param {Array} companyBills - Available company bills to link (with PO details)
 * @param {Array} purchaseOrders - Purchase orders for legacy PO reference lookup
 * @param {Array} suppliers - Available suppliers for dropdown
 * @param {Array} existingBills - Existing vendor bills to check for already-linked company bills
 * @param {Object} editingBill - Bill to edit (null for create mode)
 * @param {Function} formatCurrency - Currency formatting function
 */
const VendorBillModal = ({
  isOpen,
  onClose,
  onSave,
  onUpdate,
  companyBills = [],
  purchaseOrders = [],
  suppliers = [],
  existingBills = [],
  editingBill = null,
  formatCurrency
}) => {
  const { toAPIDateFormat } = useSystemSettings()

  // Determine if we're in edit mode
  const isEditMode = !!editingBill

  // Form state (invoiceNumber is auto-generated by backend)
  const [formData, setFormData] = useState({
    invoiceDate: new Date().toISOString().split('T')[0],
    dueDate: '',
    supplierId: '',
    invoiceAmount: '',
    notes: ''
  })

  // Selected company bills
  const [selectedBills, setSelectedBills] = useState(new Set())
  const [submitting, setSubmitting] = useState(false)
  const [error, setError] = useState('')

  // Create a lookup for PO details by ID
  const poLookup = useMemo(() => {
    const lookup = {}
    purchaseOrders.forEach(po => {
      lookup[po.id] = po
    })
    return lookup
  }, [purchaseOrders])

  // Reset form when modal opens or populate with editing data
  useEffect(() => {
    if (isOpen) {
      if (editingBill) {
        // Edit mode - populate form with existing bill data
        setFormData({
          invoiceDate: editingBill.invoice_date
            ? new Date(editingBill.invoice_date).toISOString().split('T')[0]
            : new Date().toISOString().split('T')[0],
          dueDate: editingBill.due_date
            ? new Date(editingBill.due_date).toISOString().split('T')[0]
            : '',
          supplierId: editingBill.supplier_id?.toString() || '',
          invoiceAmount: editingBill.invoice_amount?.toString() || '',
          notes: editingBill.notes || ''
        })
        // Pre-select linked company bills (new workflow) or fall back to PO-based lookup (legacy)
        if (editingBill.covers_company_bills && editingBill.covers_company_bills.length > 0) {
          setSelectedBills(new Set(editingBill.covers_company_bills))
        } else if (editingBill.covers_purchase_orders && editingBill.covers_purchase_orders.length > 0) {
          // Legacy: Find company bills for these PO IDs
          const linkedBillIds = companyBills
            .filter(cb => editingBill.covers_purchase_orders.includes(cb.purchase_order_id))
            .map(cb => cb.id)
          setSelectedBills(new Set(linkedBillIds))
        } else {
          setSelectedBills(new Set())
        }
      } else {
        // Create mode - reset to defaults
        setFormData({
          invoiceDate: new Date().toISOString().split('T')[0],
          dueDate: '',
          supplierId: '',
          invoiceAmount: '',
          notes: ''
        })
        setSelectedBills(new Set())
      }
      setError('')
    }
  }, [isOpen, editingBill, companyBills])

  // Get company bill IDs that are already linked to vendor bills (excluding current bill if editing)
  const linkedCompanyBillIds = useMemo(() => {
    const ids = new Set()
    existingBills
      .filter(b => {
        // Only vendor bills with linked company bills
        if (b.bill_type !== 'vendor') return false
        // In edit mode, exclude the current bill so its linked bills appear available
        if (isEditMode && b.id === editingBill.id) return false
        return true
      })
      .forEach(b => {
        // Check covers_company_bills (new workflow)
        if (b.covers_company_bills && Array.isArray(b.covers_company_bills)) {
          b.covers_company_bills.forEach(cbId => ids.add(cbId))
        }
        // Also check covers_purchase_orders for legacy data
        // Find company bills for those POs and mark them as linked
        if (b.covers_purchase_orders && Array.isArray(b.covers_purchase_orders)) {
          companyBills
            .filter(cb => b.covers_purchase_orders.includes(cb.purchase_order_id))
            .forEach(cb => ids.add(cb.id))
        }
      })
    return ids
  }, [existingBills, companyBills, isEditMode, editingBill])

  // Filter company bills: show "sent" bills that aren't linked to other vendor bills
  // In edit mode, always include bills currently linked to this bill
  const availableCompanyBills = useMemo(() => {
    if (!isOpen) return []

    // Get currently linked bill IDs for this bill (in edit mode)
    const currentlyLinkedBillIds = isEditMode && editingBill
      ? new Set(
          editingBill.covers_company_bills ||
          companyBills
            .filter(cb => editingBill.covers_purchase_orders?.includes(cb.purchase_order_id))
            .map(cb => cb.id)
        )
      : new Set()

    return companyBills.filter(cb => {
      // Always include bills currently linked to this vendor bill
      if (currentlyLinkedBillIds.has(cb.id)) return true

      // Must be "sent" status (not draft) - or if bill_status not set, allow all for backward compat
      const isSent = !cb.bill_status || cb.bill_status === 'sent'
      // Not already linked to another vendor bill
      const notLinked = !linkedCompanyBillIds.has(cb.id)

      return isSent && notLinked
    })
  }, [companyBills, linkedCompanyBillIds, isOpen, isEditMode, editingBill])

  // Group available company bills by supplier
  const billsBySupplier = useMemo(() => {
    const grouped = {}
    availableCompanyBills.forEach(cb => {
      const supplierId = cb.supplier_id || 'unknown'
      if (!grouped[supplierId]) {
        grouped[supplierId] = {
          supplierId,
          supplierName: cb.supplier_name || 'Unknown Supplier',
          bills: []
        }
      }
      grouped[supplierId].bills.push(cb)
    })
    return Object.values(grouped)
  }, [availableCompanyBills])

  // Filter company bills when supplier is selected
  const filteredBills = useMemo(() => {
    if (!formData.supplierId) return availableCompanyBills
    return availableCompanyBills.filter(cb =>
      cb.supplier_id === parseInt(formData.supplierId)
    )
  }, [availableCompanyBills, formData.supplierId])

  // Calculate total of selected company bills
  const selectedTotal = useMemo(() => {
    return filteredBills
      .filter(cb => selectedBills.has(cb.id))
      .reduce((sum, cb) => sum + (parseFloat(cb.invoice_amount) || 0), 0)
  }, [filteredBills, selectedBills])

  // Handle supplier change - clear selected bills for other suppliers
  const handleSupplierChange = (supplierId) => {
    setFormData(prev => ({ ...prev, supplierId }))
    // Clear selections when supplier changes
    setSelectedBills(new Set())
  }

  // Toggle company bill selection
  const toggleBill = (billId) => {
    setSelectedBills(prev => {
      const next = new Set(prev)
      if (next.has(billId)) {
        next.delete(billId)
      } else {
        next.add(billId)
      }
      return next
    })
  }

  // Select all bills for current supplier
  const selectAllBills = () => {
    setSelectedBills(new Set(filteredBills.map(cb => cb.id)))
  }

  // Clear all selections
  const clearSelections = () => {
    setSelectedBills(new Set())
  }

  // Get PO reference for a company bill
  const getPOReference = (companyBill) => {
    if (companyBill.order_number) return companyBill.order_number
    const po = poLookup[companyBill.purchase_order_id]
    return po?.orderNumber || po?.order_number || `PO-${companyBill.purchase_order_id}`
  }

  // Handle form submission (create or update)
  const handleSubmit = async (e) => {
    e.preventDefault()
    setError('')

    // Validation
    if (!formData.supplierId) {
      setError('Please select a supplier')
      return
    }
    if (selectedBills.size === 0) {
      setError('Please select at least one company bill')
      return
    }
    if (!formData.invoiceAmount || parseFloat(formData.invoiceAmount) <= 0) {
      setError('Please enter a valid invoice amount')
      return
    }

    setSubmitting(true)

    try {
      if (isEditMode) {
        // Update existing vendor bill - use new coversCompanyBills field
        const updateData = {
          invoiceDate: formData.invoiceDate,
          dueDate: formData.dueDate || null,
          invoiceAmount: parseFloat(formData.invoiceAmount),
          notes: formData.notes.trim(),
          coversCompanyBills: Array.from(selectedBills)
        }
        await onUpdate(editingBill.id, updateData)
      } else {
        // Create new vendor bill with coversCompanyBills
        const vendorBillData = {
          // invoiceNumber is auto-generated by backend (format: VB-YYYY-NNNNN)
          invoiceDate: formData.invoiceDate,
          dueDate: formData.dueDate || null,
          supplierId: parseInt(formData.supplierId),
          invoiceAmount: parseFloat(formData.invoiceAmount),
          notes: formData.notes.trim(),
          coversCompanyBills: Array.from(selectedBills),
          billType: 'vendor'
        }
        await onSave(vendorBillData)
      }
    } catch (err) {
      setError(err.message || `Failed to ${isEditMode ? 'update' : 'create'} vendor bill`)
    } finally {
      setSubmitting(false)
    }
  }

  // Get selected supplier name
  const selectedSupplier = suppliers.find(s => s.id === parseInt(formData.supplierId))

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title={isEditMode ? `Edit Vendor Bill - ${editingBill?.invoice_number}` : 'Create Vendor Bill'}
      size="lg"
    >
      <form onSubmit={handleSubmit} className="p-5">
        {error && (
          <div className="flex items-center gap-2 px-4 py-3 mb-5 bg-red-50 border border-red-200 text-red-700 text-sm">
            <AlertTriangle size={16} />
            <span>{error}</span>
          </div>
        )}

        {/* Bill Details Section */}
        <div className="form-section">
          <div className="form-section-title">
            <Receipt size={16} />
            Bill Details
          </div>

          <div className="form-grid p-5">
            <div className="form-group">
              <label>Invoice Number</label>
              {isEditMode ? (
                <div className="px-3 py-2 bg-slate-100 border border-slate-200 text-sm">
                  <span className="font-semibold text-slate-800">{editingBill?.invoice_number}</span>
                </div>
              ) : (
                <div className="flex flex-col gap-1 px-3 py-2 bg-slate-50 border border-slate-200 text-sm">
                  <span className="inline-block px-2 py-0.5 bg-blue-100 text-blue-700 text-xs font-semibold w-fit">Auto-generated</span>
                  <span className="text-slate-500 text-xs">Format: VB-{new Date().getFullYear()}-XXXXX</span>
                </div>
              )}
            </div>

            <div className="form-group">
              <label htmlFor="supplierId">Supplier *</label>
              <select
                id="supplierId"
                value={formData.supplierId}
                onChange={(e) => handleSupplierChange(e.target.value)}
                required
                disabled={isEditMode}
              >
                <option value="">Select Supplier</option>
                {suppliers.map(supplier => (
                  <option key={supplier.id} value={supplier.id}>
                    {supplier.name}
                  </option>
                ))}
              </select>
              {isEditMode && (
                <span className="text-xs text-slate-400 italic">Supplier cannot be changed when editing</span>
              )}
            </div>

            <div className="form-group">
              <DateInput
                label="Invoice Date *"
                value={formData.invoiceDate || ''}
                onChange={(value) => setFormData(prev => ({
                  ...prev,
                  invoiceDate: value || ''
                }))}
                required
              />
            </div>

            <div className="form-group">
              <DateInput
                label="Due Date"
                value={formData.dueDate || ''}
                onChange={(value) => setFormData(prev => ({
                  ...prev,
                  dueDate: value || ''
                }))}
                minDate={formData.invoiceDate || ''}
              />
            </div>

            <div className="form-group">
              <label htmlFor="invoiceAmount">Invoice Amount *</label>
              <input
                type="number"
                id="invoiceAmount"
                value={formData.invoiceAmount}
                onChange={(e) => setFormData(prev => ({ ...prev, invoiceAmount: e.target.value }))}
                placeholder="0.000"
                step="0.001"
                min="0"
                required
              />
            </div>

            <div className="form-group">
              <label>Company Bills Total (Selected)</label>
              <div className="px-3 py-2.5 bg-emerald-50 border border-emerald-200 text-emerald-700 font-semibold text-sm">
                {formatCurrency(selectedTotal)}
              </div>
            </div>
          </div>

          <div className="form-group px-5 pb-5">
            <label htmlFor="notes">Notes</label>
            <textarea
              id="notes"
              value={formData.notes}
              onChange={(e) => setFormData(prev => ({ ...prev, notes: e.target.value }))}
              placeholder="Optional notes about this vendor bill..."
              rows={2}
            />
          </div>
        </div>

        {/* Company Bills Section */}
        <div className="form-section mt-5">
          <div className="form-section-title">
            <Link2 size={16} />
            Link Company Bills
            {formData.supplierId && (
              <span className="ml-auto text-xs font-normal text-slate-500 normal-case tracking-normal">
                {selectedBills.size} of {filteredBills.length} selected
              </span>
            )}
          </div>

          <div className="p-5">
            {!formData.supplierId ? (
              <div className="flex flex-col items-center justify-center gap-3 py-8 bg-slate-50 border border-slate-200 text-slate-400">
                <FileText size={32} />
                <p className="m-0 text-sm">Select a supplier to see available company bills</p>
              </div>
            ) : filteredBills.length === 0 ? (
              <div className="flex flex-col items-center justify-center gap-3 py-8 bg-amber-50 border border-amber-200 text-amber-600">
                <AlertTriangle size={32} />
                <p className="m-0 text-sm font-medium">No eligible company bills for {selectedSupplier?.name}</p>
                <span className="text-xs text-amber-500">Only "sent" company bills not linked to other vendor bills are shown</span>
              </div>
            ) : (
              <>
                <div className="flex gap-2 mb-3">
                  <button
                    type="button"
                    className="btn btn-outline btn-sm"
                    onClick={selectAllBills}
                  >
                    Select All
                  </button>
                  <button
                    type="button"
                    className="btn btn-outline btn-sm"
                    onClick={clearSelections}
                  >
                    Clear
                  </button>
                </div>

                <div className="flex flex-col gap-2 max-h-[300px] overflow-y-auto">
                {filteredBills.map(cb => {
                  const isSelected = selectedBills.has(cb.id)
                  const isCurrentlyLinked = isEditMode && (
                    editingBill?.covers_company_bills?.includes(cb.id) ||
                    editingBill?.covers_purchase_orders?.includes(cb.purchase_order_id)
                  )
                  const billStatus = cb.bill_status || 'sent'
                  return (
                    <div
                      key={cb.id}
                      className={`flex items-center gap-3 p-3 border cursor-pointer transition-all ${
                        isSelected
                          ? 'bg-blue-50 border-blue-400 ring-1 ring-blue-400'
                          : isCurrentlyLinked
                            ? 'bg-emerald-50 border-emerald-300'
                            : 'bg-white border-slate-200 hover:border-slate-300 hover:bg-slate-50'
                      }`}
                      onClick={() => toggleBill(cb.id)}
                    >
                      <div className={`flex-shrink-0 ${isSelected ? 'text-blue-600' : 'text-slate-400'}`}>
                        {isSelected ? (
                          <CheckSquare size={20} />
                        ) : (
                          <Square size={20} />
                        )}
                      </div>
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 flex-wrap">
                          <span className="font-semibold text-slate-800 text-sm">{cb.invoice_number}</span>
                          <span className={`px-1.5 py-0.5 text-[10px] font-semibold uppercase ${
                            billStatus === 'sent'
                              ? 'bg-green-100 text-green-700'
                              : 'bg-slate-100 text-slate-600'
                          }`}>
                            {billStatus}
                          </span>
                          {isCurrentlyLinked && (
                            <span className="px-1.5 py-0.5 bg-emerald-100 text-emerald-700 text-[10px] font-semibold uppercase">Linked</span>
                          )}
                        </div>
                        <div className="flex items-center gap-3 text-xs text-slate-500 mt-1">
                          <span>PO: {getPOReference(cb)}</span>
                          <span>{new Date(cb.invoice_date).toLocaleDateString()}</span>
                        </div>
                      </div>
                      <div className="flex-shrink-0 font-semibold text-slate-800 text-sm">
                        {formatCurrency(cb.invoice_amount)}
                      </div>
                    </div>
                  )
                })}
              </div>

                {/* Amount Comparison */}
                {selectedBills.size > 0 && formData.invoiceAmount && (
                  <div className="flex items-center gap-3 p-3 mt-3 bg-slate-100 border border-slate-200">
                    <Calculator size={16} className="text-slate-400" />
                    <div className="flex flex-wrap items-center gap-4 text-sm">
                      <span className="text-slate-600">Vendor Bill: <strong>{formatCurrency(parseFloat(formData.invoiceAmount))}</strong></span>
                      <span className="text-slate-600">Company Bills Total: <strong>{formatCurrency(selectedTotal)}</strong></span>
                      {Math.abs(parseFloat(formData.invoiceAmount) - selectedTotal) >= 0.01 && (
                        <span className={`font-semibold ${parseFloat(formData.invoiceAmount) > selectedTotal ? 'text-amber-600' : 'text-red-600'}`}>
                          Difference: {formatCurrency(Math.abs(parseFloat(formData.invoiceAmount) - selectedTotal))}
                        </span>
                      )}
                    </div>
                  </div>
                )}
              </>
            )}
          </div>
        </div>

        {/* Form Actions */}
        <div className="form-actions mt-5">
          <button
            type="button"
            className="btn btn-outline"
            onClick={onClose}
            disabled={submitting}
          >
            Cancel
          </button>
          <button
            type="submit"
            className="btn btn-primary"
            disabled={submitting || selectedBills.size === 0}
          >
            {submitting
              ? (isEditMode ? 'Updating...' : 'Creating...')
              : (isEditMode ? 'Update Vendor Bill' : 'Create Vendor Bill')
            }
          </button>
        </div>
      </form>
    </Modal>
  )
}

export default VendorBillModal
