import React, { createContext, useContext, useState, useEffect } from 'react'
import { useAuth } from './AuthContext'

// Localization Context
const LocalizationContext = createContext({})

export const useLocalization = () => {
  const context = useContext(LocalizationContext)
  if (!context) {
    throw new Error('useLocalization must be used within a LocalizationProvider')
  }
  return context
}

// Language translations
const translations = {
  en: {
    // Common
    loading: 'Loading...',
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    view: 'View',
    search: 'Search',
    filter: 'Filter',
    export: 'Export',
    exportCSV: 'Export to CSV',
    exportExcel: 'Export to Excel',
    print: 'Print',
    close: 'Close',
    submit: 'Submit',
    reset: 'Reset',
    confirm: 'Confirm',
    yes: 'Yes',
    no: 'No',
    ok: 'OK',
    error: 'Error',
    success: 'Success',
    warning: 'Warning',
    info: 'Information',
    date: 'Date',
    actions: 'Actions',
    all: 'All',
    new: 'New',
    add: 'Add',
    update: 'Update',
    create: 'Create',
    remove: 'Remove',
    select: 'Select',
    choose: 'Choose',
    apply: 'Apply',
    clear: 'Clear',
    refresh: 'Refresh',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    continue: 'Continue',
    finish: 'Finish',
    done: 'Done',
    start: 'Start',
    stop: 'Stop',
    pause: 'Pause',
    resume: 'Resume',
    adjust: 'Adjust',
    history: 'History',
    more: 'More',
    orders: 'Orders',
    columns: 'Columns',
    rows: 'Rows',
    draft: 'Draft',
    active: 'Active',
    inactive: 'Inactive',
    expired: 'Expired',
    pending: 'Pending',
    approved: 'Approved',
    rejected: 'Rejected',
    cancelled: 'Cancelled',
    completed: 'Completed',
    processing: 'Processing',
    delivered: 'Delivered',
    received: 'Received',
    paid: 'Paid',
    unpaid: 'Unpaid',
    overdue: 'Overdue',
    available: 'Available',
    unavailable: 'Unavailable',
    enabled: 'Enabled',
    disabled: 'Disabled',
    online: 'Online',
    offline: 'Offline',
    home: 'Home',
    menu: 'Menu',
    navigation: 'Navigation',
    administration: 'Administration',
    management: 'Management',
    dashboard: 'Dashboard',
    
    // Navigation
    customers: 'Customers',
    suppliers: 'Suppliers',
    inventory: 'Inventory',
    sales: 'Sales',
    purchase: 'Purchase',
    contracts: 'Contracts',
    reports: 'Reports',
    settings: 'Settings',
    profile: 'Profile',
    logout: 'Logout',
    
    // Dashboard
    totalCustomers: 'Total Customers',
    totalSales: 'Total Sales',
    pendingOrders: 'Pending Orders',
    lowStock: 'Low Stock Items',
    recentTransactions: 'Recent Transactions',
    monthlyRevenue: 'Monthly Revenue',
    
    // Customer Management
    addCustomer: 'Add Customer',
    editCustomer: 'Edit Customer',
    customerName: 'Customer Name',
    contactPerson: 'Contact Person',
    email: 'Email',
    phone: 'Phone',
    address: 'Address',
    city: 'City',
    country: 'Country',
    creditLimit: 'Credit Limit',
    paymentTerms: 'Payment Terms',
    customerDetails: 'Customer Details',
    createOrder: 'Create Order',
    viewContract: 'View Contract',
    customerManagement: 'Customer Management',
    customerSubtitle: 'Manage fuel customers and delivery contracts',
    customer: 'Customer',
    contact: 'Contact',
    order: 'Order',
    contract: 'Contract',
  
    // Inventory Management
    materialName: 'Material Name',
    category: 'Category',
    unit: 'Unit',
    currentStock: 'Current Stock',
    minimumStock: 'Minimum Stock',
    standardPrice: 'Standard Price',
    supplier: 'Supplier',
    lastUpdated: 'Last Updated',
    items: 'Items',
    paymentStatus: 'Payment Status',
    material: 'Material',
    inventory: 'Inventory',
    volume: 'Volume',
    price: 'Price',
    value: 'Value',
    addMaterial: 'Add Material',
    editMaterial: 'Edit Material',
    deleteMaterial: 'Delete Material',
    viewMaterial: 'View Material',
    stockValue: 'Stock Value',
    stockMovement: 'Stock Movement',
    stockIn: 'Stock In',
    stockOut: 'Stock Out',
    stockAdjustment: 'Stock Adjustment',
    reorderLevel: 'Reorder Level',
    scrapMaterialsSubtitle: 'Manage scrap materials',
    scrapMaterials: 'Scrap Materials',
    materialCode: 'Material Code',
    materialType: 'Material Type',
    subcategory: 'Subcategory',
    brand: 'Brand',
    model: 'Model',
    specification: 'Specification',
    description: 'Description',
    unitPrice: 'Unit Price',
    maximumStock: 'Maximum Stock',
    sellingPrice: 'Selling Price',
    purchasePrice: 'Purchase Price',

    startSorting: 'Start Sorting',
    stopSorting: 'Stop Sorting',
    checkProgress: 'Check Progress',
    weight: 'Weight',
    gradePurity: 'Grade Purity',
    purchaseRate: 'Purchase Rate',
    sellingRate: 'Selling Rate',
    marketRate: 'Market Rate',
    currentValue: 'Current Value',
    potentialProfit: 'Potential Profit',
    inventoryOverview: 'Inventory Overview',
    completeInventorySummary: 'Complete inventory summary',
    materialInventorySubtitle: 'Track material inventory and processing',
    stockMovementsSubtitle: 'Track inventory in and out movements',
    readyToSell: 'Ready to Sell',
    sortingRequired: 'Sorting Required',
    sellNow: 'Sell Now',
    goodStock: 'Good Stock',
    critical: 'Critical',
    outOfStock: 'Out of Stock',
    noCustomersFound: 'No customers found',
    noContractsFound: 'No contracts found',
    noMaterialsFound: 'No materials found',
    noMovementsFound: 'No stock movements found',
    noSuppliersFound: 'No suppliers found',
    loadingContracts: 'Loading contracts...',
    
    // Sales & Purchase
    orderNumber: 'Order Number',
    orderDate: 'Order Date',
    deliveryDate: 'Delivery Date',
    quantity: 'Quantity',
    rate: 'Rate',
    amount: 'Amount',
    subtotal: 'Subtotal',
    tax: 'Tax',
    total: 'Total',
    salesOrders: 'Sales Management',
    salesOrdersSubtitle: 'Manage sales orders and invoices',
    searchSalesOrders: 'Search Sales Orders',
    salesOrder: 'Sales Order',
    
    // Contracts
    contractNumber: 'Contract Number',
    startDate: 'Start Date',
    endDate: 'End Date',
    contractType: 'Contract Type',
    status: 'Status',
    active: 'Active',
    expired: 'Expired',
    pending: 'Pending',
    terms: 'Terms',
    areas: 'Areas',
    contractId: 'Contract ID',
    contractManagement: 'Contract Management',
    contractSubtitle: 'Manage fuel contracts',
    searchContracts: 'Search Contracts',
    contract: 'Contract',
    fuelItems: 'Fuel Items',
    
    // Financial Terms
    paymentDate: 'Payment Date',
    dueDate: 'Due Date',
    cash: 'Cash',
    credit: 'Credit',
    cheque: 'Cheque',
    bankTransfer: 'Bank Transfer',
    card: 'Card',
    expense: 'Expense',
    income: 'Income',
    profit: 'Profit',
    loss: 'Loss',
    revenue: 'Revenue',
    cost: 'Cost',
    margin: 'Margin',
    commission: 'Commission',

    // Suppliers
    totalSuppliers: 'Total Suppliers',
    addSupplier: 'Add Supplier',
    editSupplier: 'Edit Supplier',
    supplierName: 'Supplier Name',
    supplierDetails: 'Supplier Details',
    supplierManagement: 'Supplier Management',
    supplierSubtitle: 'Manage scrap material suppliers and collection partners',
    businessSuppliers: 'Business Suppliers',
    activeSuppliers: 'Active Suppliers',
    inactiveSuppliers: 'Inactive Suppliers',
    manageScrapSuppliers: 'Manage scrap suppliers',
    supplierCode: 'Supplier Code',
    supplierType: 'Supplier Type',
    totalPurchases: 'Total Purchases',
    totalRevenue: 'Total Revenue',
    addNewSupplier: 'Add New Supplier',
    supplierCreated: 'Supplier created successfully!',
    supplierUpdated: 'Supplier updated successfully!',
    supplierDeleted: 'Supplier deleted successfully!',
    createNewContract: 'Create New Contract',
    renewContract: 'Renew Contract',
    editContract: 'Edit Contract',
    
    // Settings
    generalSettings: 'General Settings',
    localizationSettings: 'Localization Settings',
    language: 'Language',
    dateFormat: 'Date Format',
    timeFormat: 'Time Format',
    currency: 'Currency',
    timezone: 'Timezone',
    firstDayOfWeek: 'First Day of Week',
    configureGlobalSettings: 'Configure Global Settings',
    configureLanguageAndRegion: 'Configure Language and Region',
    configureCulturalPreferences: 'Configure Cultural Preferences',
    appearanceSettings: 'Appearance Settings',
    customizeVisualAppearance: 'Customize Visual Appearance',
    notificationSettings: 'Notification Settings',
    configureNotificationsAndAlerts: 'Configure Notifications and Alerts',
    notificationPreferences: 'Notification Preferences',
    languagePreferenceSavedPerUser: 'Language Preference Saved Per User',
    currentSettingsInformation: 'Current Settings Information',
    settingsSource: 'Settings Source',
    isCustomized: 'Is Customized',
    resetToDefaults: 'Reset to Defaults',
    saveSettings: 'Save Settings',
    saving: 'Saving...',
    availableInFutureUpdate: 'Available in Future Update',
    lightTheme: 'Light Theme',
    darkTheme: 'Dark Theme',
    notifications: 'Notifications',
    
    // User Management
    username: 'Username',
    password: 'Password',
    role: 'Role',
    company: 'Company',
    lastLogin: 'Last Login',
    userManagement: 'User Management',
    addUser: 'Add User',
    editUser: 'Edit User',
    vatRegistrationNumber: 'VAT Registration Number',
    
    // Inventory Management
    openingStock: 'Opening Stock',
    openingStockValue: 'Opening Stock Value',
    openingStockDate: 'Opening Stock Date',
    setOpeningStock: 'Set Opening Stock',
    showCharts: 'Show Charts',
    hideCharts: 'Hide Charts',
    selectMaterial: 'Select Material',
    currentOpeningStock: 'Current Opening Stock',
    updateOpeningStock: 'Update Opening Stock',
    openingStockUpdated: 'Opening stock updated successfully',
    barChart: 'Bar Chart',
    lineChart: 'Line Chart',
    pieChart: 'Pie Chart',
    
    // Wastage Management
    wastageManagement: 'Wastage Management',
    trackWastageAndLosses: 'Track material wastage and losses',
    reportWastage: 'Report Wastage',
    viewAnalytics: 'View Analytics',
    totalWastages: 'Total Wastages',
    totalWasteCost: 'Total Waste Cost',
    pendingApproval: 'Pending Approval',
    approved: 'Approved',
    rejected: 'Rejected',
    wasteType: 'Waste Type',
    wastageRecords: 'Wastage Records',
    noWastageRecords: 'No wastage records found',
    wastageAnalytics: 'Wastage Analytics',
    wastageByType: 'Wastage by Type',
    monthlyWastageTrends: 'Monthly Wastage Trends',
    loadingWastageData: 'Loading wastage data...',
    allTypes: 'All Types',
    totalCost: 'Total Cost',
    
    // Validation Messages
    required: 'This field is required',
    invalidEmail: 'Please enter a valid email address',
    invalidPhone: 'Please enter a valid phone number',
    invalidDate: 'Please enter a valid date',
    invalidNumber: 'Please enter a valid number',
    minLength: 'Minimum {min} characters required',
    maxLength: 'Maximum {max} characters allowed',
    minValue: 'Minimum value allowed {min}',
    maxValue: 'Maximum value allowed {max}',
    passwordMismatch: 'Passwords do not match',
    passwordTooWeak: 'Password is too weak',
    fieldRequired: 'Field is required',
    pleaseSelect: 'Please select',
    pleaseEnter: 'Please enter',
    confirmDelete: 'Are you sure you want to delete this item?',
    errorDeleting: 'Error deleting item',
    errorSaving: 'Error saving data',
    fillRequiredFields: 'Please fill in all required fields',
    
    // Success Messages
    customerAdded: 'Customer added successfully',
    customerUpdated: 'Customer updated successfully',
    customerDeleted: 'Customer deleted successfully',
    orderCreated: 'Order created successfully',
    settingsSaved: 'Settings saved successfully',
    saveSuccess: 'Saved successfully',
    updateSuccess: 'Updated successfully',
    deleteSuccess: 'Deleted successfully',
    addSuccess: 'Added successfully',
    createSuccess: 'Created successfully',
    contractCreated: 'Contract created successfully',
    contractUpdated: 'Contract updated successfully',
    passwordChanged: 'Password changed successfully',
    profileUpdated: 'Profile updated successfully',
    
    // Error Messages
    somethingWentWrong: 'Something went wrong. Please try again.',
    networkError: 'Network error. Please check your connection.',
    unauthorized: 'You are not authorized to perform this action.',
    serverError: 'Server error. Please try again later.',
    accessDenied: 'Access denied',
    notFound: 'Not found',
    alreadyExists: 'Already exists',
    invalidCredentials: 'Invalid credentials',
    sessionExpired: 'Session expired',
    operationFailed: 'Operation failed',
    dataCorrupted: 'Data is corrupted',
    insufficientPermissions: 'Insufficient permissions',
    
    // Business Specific
    oilTrading: 'Oil Trading',
    scrapMaterials: 'Scrap Materials',
    fuelInventory: 'Fuel Inventory',
    materialInventory: 'Material Inventory',
    tankCapacity: 'Tank Capacity',
    currentLevel: 'Current Level',
    materialGrade: 'Material Grade',
    weightPerUnit: 'Weight per Unit',
    fuelType: 'Fuel Type',
    oilType: 'Oil Type',
    viscosity: 'Viscosity',
    density: 'Density',
    purity: 'Purity',
    quality: 'Quality',
    barrel: 'Barrel',
    liter: 'Liter',
    gallon: 'Gallon',
    ton: 'Ton',
    kilogram: 'Kilogram',
    gram: 'Gram',
    meter: 'Meter',
    centimeter: 'Centimeter',
    fromLastMonth: 'From Last Month',
    fromLastWeek: 'From Last Week',
    fromYesterday: 'From Yesterday',
    increase: 'Increase',
    decrease: 'Decrease',
    noChange: 'No Change',
    percentage: 'Percentage',
    hourAgo: 'Hour Ago',
    hoursAgo: '{hours} Hours Ago',
    minuteAgo: 'Minute Ago',
    minutesAgo: '{minutes} Minutes Ago',
    dayAgo: 'Day Ago',
    daysAgo: '{days} Days Ago',
    weekAgo: 'Week Ago',
    weeksAgo: '{weeks} Weeks Ago',
    yearToDate: 'Year to Date',
    thisWeek: 'This Week',
    lastWeek: 'Last Week',
    nextWeek: 'Next Week',
    thisMonth: 'This Month',
    nextMonth: 'Next Month',
    thisYear: 'This Year',
    nextYear: 'Next Year',
    morning: 'Morning',
    night: 'Night',
    
    monthlyVolume: 'Monthly Volume',
    weeklyVolume: 'Weekly Volume',
    dailyVolume: 'Daily Volume',
    yearlyVolume: 'Yearly Volume',
    totalValue: 'Total Value',
    totalVolume: 'Total Volume',
    totalCollected: 'Total Collected',
    totalPending: 'Total Pending',

    regularPartners: 'Regular Partners',
    businessPartners: 'Business Partners',
    specialization: 'Specialization',

    advancedFilters: 'Advanced Filters',
    advancedSearch: 'Advanced Search',
    columns: 'Columns',
    rows: 'Rows',
    viewDetails: 'View Details',
    walkIn: 'Walk-in',
    project: 'Project',
    totalProfit: 'Total Profit',
    topCustomers: 'Top Customers',
    topProducts: 'Top Products',
    salesGrowth: 'Sales Growth',
    
    // Page Headers and Titles
    customerManagementTitle: 'Customer Management',
    contractManagementTitle: 'Contract Management', 
    purchaseOrdersTitle: 'Purchase Orders',
    inventoryManagementTitle: 'Inventory Management',
    supplierManagementTitle: 'Supplier Management',
    materialInventoryManagementTitle: 'Material Inventory Management',
    
    // Subtitles and Descriptions
    manageFuelCustomersSubtitle: 'Manage fuel customers and delivery contracts',
    manageFuelContractsSubtitle: 'Manage fuel supply contracts and agreements',
    manageVendorOrdersSubtitle: 'Manage vendor orders and procurement for',
    trackStockLevelsSubtitle: 'Track stock levels, movements, and material status',
    trackScrapMaterialsSubtitle: 'Track scrap materials, storage, and processing status',
    
    // Button Labels
    addCustomerBtn: 'Add Customer',
    newContractBtn: 'New Contract',
    newPurchaseOrderBtn: 'New Purchase Order',
    stockReportBtn: 'Stock Report',
    stockAdjustmentBtn: 'Stock Adjustment',
    processMaterialsBtn: 'Process Materials',
    addSupplierBtn: 'Add Supplier',
    
    // Loading Messages
    loadingCustomers: 'Loading customers...',
    loadingSuppliers: 'Loading suppliers...',
    loadingPurchaseOrders: 'Loading purchase orders...',
    loadingInventory: 'Loading inventory...',
    
    // Dashboard Cards
    activeContracts: 'Active Contracts',
    expiringSoon: 'Expiring Soon',
    pendingRenewal: 'Pending Renewal',
    currentlyRunning: 'Currently running',
    withinDays: 'Within 30 days',
    actionRequired: 'Action required',
    
    // Form Section Headers
    basicInformation: 'Basic Information',
    contactInformation: 'Contact Information',
    addressInformation: 'Address Information',
    businessTerms: 'Business Terms',
    businessDetails: 'Business Details',
    contractTermsConditions: 'Contract Terms & Conditions',
    orderInformation: 'Order Information',
    customerDetails: 'Customer Details',
    vendorInformation: 'Vendor Information',
    materialRatesPricing: 'Material Rates & Pricing',
    orderItems: 'Order Items',
    orderTotals: 'Order Totals',
    additionalInformation: 'Additional Information',
    bankingInformation: 'Banking Information',
    
    // Form Field Labels
    customerNameRequired: 'Customer Name *',
    customerTypeRequired: 'Customer Type *',
    contactPersonLabel: 'Contact Person',
    phoneNumberRequired: 'Phone Number *',
    emailAddress: 'Email Address',
    streetAddress: 'Street Address',
    cityLabel: 'City',
    regionLabel: 'Region',
    creditLimitOMR: 'Credit Limit (OMR)',
    paymentTermsDays: 'Payment Terms (days)',
    specialTermsConditions: 'Special Terms & Conditions',
    supplierCodeRequired: 'Supplier Code *',
    supplierNameRequired: 'Supplier Name *',
    supplierTypeLabel: 'Supplier Type',
    businessRegistration: 'Business Registration',
    nationalIdLabel: 'National ID',
    taxNumberLabel: 'Tax Number',
    bankNameLabel: 'Bank Name',
    accountNumberLabel: 'Account Number',
    ibanLabel: 'IBAN',
    
    // Modal Titles
    editCustomerModal: 'Edit Customer',
    addNewCustomerModal: 'Add New Customer',
    customerDetailsModal: 'Customer Details',
    contractDetailsModal: 'Contract Details',
    editContractModal: 'Edit Contract',
    createNewContractModal: 'Create New Contract',
    addNewSupplierModal: 'Add New Supplier',
    editSupplierModal: 'Edit Supplier',
    supplierDetailsModal: 'Supplier Details',
    createSalesOrderModal: 'Create Sales Order',
    createPurchaseOrderModal: 'Create Purchase Order',
    
    // Status Labels
    readyToSellStatus: 'Ready to Sell',
    processingStatus: 'Processing',
    sortingRequiredStatus: 'Sorting Required',
    contractCustomer: 'Contract Customer',
    highValueStatus: 'High Value',
    lowStockStatus: 'Low Stock',
    criticalStatus: 'Critical',
    goodStockStatus: 'Good Stock',
    
    // Action Buttons
    viewDetailsBtn: 'View Details',
    sellNowBtn: 'Sell Now',
    checkProgressBtn: 'Check Progress',
    startSortingBtn: 'Start Sorting',
    createOrderBtn: 'Create Order',
    viewContractBtn: 'View Contract',
    renewContractBtn: 'Renew Contract',
    manageSectionsBtn: 'Manage Sections',
    optimizeLayoutBtn: 'Optimize Layout',
    
    // Table Column Headers
    orderNumberHeader: 'Order Number',
    vendorHeader: 'Vendor',
    expectedDeliveryHeader: 'Expected Delivery',
    itemsHeader: 'Items',
    totalAmountHeader: 'Total Amount',
    materialHeader: 'Material',
    weightHeader: 'Weight',
    gradePurityHeader: 'Grade Purity',
    purchaseRateHeader: 'Purchase Rate',
    marketRateHeader: 'Market Rate',
    currentValueHeader: 'Current Value',
    potentialProfitHeader: 'Potential Profit',
    
    // Inventory Categories
    engineOils: 'Engine Oils',
    diesel: 'Diesel',
    emptyDrums: 'Empty Drums',
    crudeSludge: 'Crude Sludge',
    
    // Material Grades
    commercialGrade: 'Commercial Grade',
    premiumUnleaded: 'Premium Unleaded',
    multiGrade: 'Multi-Grade',
    gradeA: 'Grade A',
    recycled: 'Recycled',
    mixedGrade: 'Mixed Grade',
    clean: 'Clean',
    
    // Time and Date
    todayTime: 'Today',
    yesterdayTime: 'Yesterday',
    timeAgo: 'ago',
    
    // Units and Measurements
    litersUnit: 'L',
    kilogramsUnit: 'KG',
    piecesUnit: 'pcs',
    capacityUnit: 'capacity',
    perLiter: 'per liter',
    perBarrel: 'per barrel',
    perKilogram: 'per KG',
    
    // Alerts and Messages
    lowStockAlert: 'Low Stock Alert',
    storageCapacityAlert: 'Storage Capacity Alert',
    marketUpdate: 'Market Update',
    noContractFound: 'No Contract Found',
    noSpecialRatesConfigured: 'No Special Rates Configured',
    noMaterialRatesAdded: 'No Material Rates Added',
    accessDeniedMessage: 'Access Denied',
    permissionDeniedMessage: 'You don\'t have permission to access system settings.',
    
    // Contract Types
    fuelSupplyContract: 'Fuel Supply Contract',
    bulkSupplyContract: 'Bulk Supply Contract',
    exclusiveSupplyContract: 'Exclusive Supply Contract',
    projectBasedContract: 'Project-Based Contract',
    
    // Payment Terms
    net15Days: 'Net 15 Days',
    net30Days: 'Net 30 Days', 
    net45Days: 'Net 45 Days',
    net60Days: 'Net 60 Days',
    cashOnDelivery: 'Cash on Delivery',
    advancePayment: 'Advance Payment',
    
    // Specialization Options
    copper: 'COPPER',
    aluminum: 'ALUMINUM', 
    steel: 'STEEL',
    iron: 'IRON',
    brass: 'BRASS',
    electronics: 'ELECTRONICS',
    preciousMetals: 'PRECIOUS_METALS',
    cables: 'CABLES',
    
    // Collection Areas
    muscat: 'Muscat',
    bawshar: 'Bawshar',
    ruwi: 'Ruwi',
    mutrah: 'Mutrah',
    seeb: 'Seeb',
    alKhuwair: 'Al Khuwair',
    sohar: 'Sohar',
    
    // Performance Metrics
    reliabilityScore: 'Reliability Score',
    qualityRating: 'Quality Rating',
    averageRate: 'Average Rate',
    notSpecified: 'Not specified',
    notProvided: 'Not provided',
    
    // Tab Labels
    overviewTab: 'Overview',
    materialsTab: 'Materials',
    stockMovementsTab: 'Stock Movements',
    materialsInventoryTab: 'Materials Inventory',
    storageManagementTab: 'Storage Management',
    
    // Form Placeholders
    enterCustomerName: 'Enter customer name',
    enterContactPerson: 'Enter contact person name',
    enterStreetAddress: 'Enter street address',
    enterCity: 'Enter city',
    enterRegion: 'Enter region/governorate',
    selectCustomer: 'Choose a customer...',
    selectMaterial: 'Select material...',
    selectVendor: 'Select Vendor...',
    
    // Confirmation Messages
    confirmDeleteCustomer: 'Are you sure you want to delete this customer?',
    confirmDeleteSupplier: 'Are you sure you want to delete this supplier?',
    confirmDeleteContract: 'Are you sure you want to delete this contract?',
    
    //Other keys
    generateInvoice: 'Generate Invoice',
    noOrdersFound: 'No orders found',
    orderId: 'Order ID',
    adjustStock: 'Adjust Stock',
    viewHistory: 'View History',
    purchaseOrders: 'Purchase Orders',
    editPurchaseOrder: 'Edit Purchase Order',
    createPurchaseOrder: 'Create Purchase Order',
    noPurchaseOrdersFound: 'No purchase orders found',
    adjustStockLevel: 'Adjust Stock Level',
    stockMovements: 'Stock Movements',
    storageManagement: 'Storage Management',
    materialInventoryManagement: 'Material Inventory Management',
    trackMaterialInventory: 'Track material inventory and processing',
    processInventory: 'Process Inventory',
    optimizeStorage: 'Optimize Storage',
    download: 'Download',
    approve: 'Approve',
    orderStatus: 'Order Status',
    orderNotes: 'Order Notes',
    contractRate: 'Contract Rate',
    createSalesOrder: 'Create Sales Order',
    expectedDeliveryDate: 'Expected Delivery Date',
    specialInstructions: 'Special Instructions',
    rateOverrideRequired: 'Rate Override Required',
    managerApprovalNeeded: 'Manager approval needed to change contracted rate',
    salesHistory: 'Sales History',
    contractInformation: 'Contract Information',
    businessInformation: 'Business Information',
    performanceMetrics: 'Performance Metrics',
    purchaseHistory: 'Purchase History',
    totalMaterialWeight: 'Total Material Weight',
    totalInventoryValue: 'Total Inventory Value',
    storageLocationsOverview: 'Storage Locations Overview',
    
    // Additional commonly used keys
    items: 'Items',
    payment: 'Payment',
    supplier: 'Supplier',
    customer: 'Customer',
    order: 'Order',
    orders: 'Orders',
    suppliers: 'Suppliers',
    customers: 'Customers',
    materials: 'Materials',
    inventory: 'Inventory',
    purchase: 'Purchase',
    sales: 'Sales',
    contracts: 'Contracts',
    reports: 'Reports',
    settings: 'Settings',
    profile: 'Profile',
    logout: 'Logout',
    home: 'Home',
    
    // Purchase Management - Missing Keys
    purchaseManagement: 'Purchase Management',
    newPurchaseOrder: 'New Purchase Order',
    purchaseOrders: 'Purchase Orders',
    purchaseExpenses: 'Purchase Expenses',
    managePurchaseOrders: 'Manage purchase orders and expenses',
    manageScrapMaterialPurchaseOrders: 'Manage scrap material purchase orders and track deliveries',
    manageTransportationMaintenance: 'Manage transportation, maintenance, and other purchase-related expenses',
    
    // Sales Management - Missing Keys
    salesManagement: 'Sales Management',
    newSaleOrder: 'New Sale Order',
    salesOrders: 'Sales Orders',
    invoices: 'Invoices',
    manageSalesOrders: 'Manage sales orders and invoices',
    noInvoicesGenerated: 'No invoices generated yet',
    createSalesOrdersFirst: 'Create sales orders first, then generate invoices from them',
    pendingOrders: 'Pending Orders',
    ordersToday: 'Orders (Today)',
    totalSalesToday: 'Total Sales (Today)',
    
    // Material & Inventory - Missing Keys
    materialInventoryManagement: 'Material Inventory Management',
    processmaterials: 'Process Materials',
    storageManagement: 'Storage Management',
    
    // Supplier Management - Missing Keys
    supplierManagement: 'Supplier Management',
    addSupplier: 'Add Supplier',
    totalSuppliers: 'Total Suppliers',
    
    // Table Headers and Fields - Missing Keys
    supplier: 'Supplier',
    orderId: 'Order ID',
    items: 'Items',
    payment: 'Payment',
    total: 'Total',
    amount: 'Amount',
    description: 'Description',
    category: 'Category',
    expenseId: 'Expense ID',
    customer: 'Customer',
    allCustomers: 'All Customers',
    allStatus: 'All Status',
    searchSalesOrders: 'Search Sales Orders',
    
    // Filter and Search - Missing Keys
    advancedFilters: 'Advanced Filters',
    columns: 'Columns',
    
    // Welcome and greeting messages
    welcomeBack: 'Welcome Back',
    welcomeTo: 'Welcome to',
    goodMorning: 'Good Morning',
    goodAfternoon: 'Good Afternoon',
    goodEvening: 'Good Evening',
    
    // Miscellaneous
    all: 'All',
    none: 'None',
    other: 'Other',
    unknown: 'Unknown',
    notApplicable: 'Not Applicable',
    notAvailable: 'Not Available',
    comingSoon: 'Coming Soon',
    underConstruction: 'Under Construction',
    maintenance: 'Maintenance',
    upgrade: 'Upgrade',
    version: 'Version',
    about: 'About',
    help: 'Help',
    support: 'Support',
    contact: 'Contact',
    privacy: 'Privacy',
    terms: 'Terms',
    legal: 'Legal',
    copyright: 'Copyright and Intellectual Property',
    reason: 'Reason',
    type: 'Type',
    status: 'Status',
    action: 'Action',
    reference: 'Reference',
    description: 'Description',
    details: 'Details',
  },
  
  ar: {
    // Common Actions
    loading: 'جاري التحميل...',
    save: 'حفظ',
    cancel: 'إلغاء',
    edit: 'تعديل',
    delete: 'حذف',
    view: 'عرض',
    search: 'بحث',
    filter: 'تصفية',
    export: 'تصدير',
    exportCSV: 'تصدير إلى CSV',
    exportExcel: 'تصدير إلى Excel',
    print: 'طباعة',
    close: 'إغلاق',
    submit: 'إرسال',
    reset: 'إعادة تعيين',
    confirm: 'تأكيد',
    yes: 'نعم',
    no: 'لا',
    ok: 'موافق',
    add: 'إضافة',
    update: 'تحديث',
    create: 'إنشاء',
    remove: 'إزالة',
    select: 'اختيار',
    choose: 'اختر',
    apply: 'تطبيق',
    clear: 'مسح',
    refresh: 'تحديث',
    back: 'رجوع',
    next: 'التالي',
    previous: 'السابق',
    continue: 'متابعة',
    finish: 'إنهاء',
    done: 'تم',
    start: 'بدء',
    stop: 'إيقاف',
    pause: 'إيقاف مؤقت',
    resume: 'استئناف',
    adjust: 'تعديل',
    history: 'التاريخ',
    more: 'المزيد',
    orders: 'الطلبات',
    columns: 'الأعمدة',
    rows: 'الصفوف',
    actions: 'الإجراءات',
    date: 'التاريخ',
    info: 'معلومات',
    
    // Status & States
    error: 'خطأ',
    success: 'نجح',
    warning: 'تحذير',
    info: 'معلومات',
    new: 'جديد',
    draft: 'مسودة',
    active: 'نشط',
    inactive: 'غير نشط',
    expired: 'منتهي الصلاحية',
    pending: 'معلق',
    approved: 'موافق عليه',
    rejected: 'مرفوض',
    cancelled: 'ملغي',
    completed: 'مكتمل',
    processing: 'قيد المعالجة',
    delivered: 'تم التسليم',
    received: 'تم الاستلام',
    paid: 'مدفوع',
    unpaid: 'غير مدفوع',
    overdue: 'متأخر',
    available: 'متاح',
    unavailable: 'غير متاح',
    enabled: 'مفعل',
    disabled: 'معطل',
    online: 'متصل',
    offline: 'غير متصل',
    
    // Navigation & Menu
    dashboard: 'لوحة التحكم',
    customers: 'العملاء',
    suppliers: 'الموردين',
    inventory: 'المخزون',
    sales: 'المبيعات',
    purchase: 'المشتريات',
    contracts: 'العقود',
    reports: 'التقارير',
    settings: 'الإعدادات',
    profile: 'الملف الشخصي',
    logout: 'تسجيل الخروج',
    home: 'الرئيسية',
    menu: 'القائمة',
    navigation: 'التنقل',
    administration: 'الإدارة',
    management: 'الإدارة',
    
    // Purchase Management - Missing Keys
    purchaseManagement: 'إدارة المشتريات',
    newPurchaseOrder: 'طلب شراء جديد',
    purchaseOrders: 'طلبات الشراء',
    purchaseExpenses: 'مصروفات الشراء',
    managePurchaseOrders: 'إدارة طلبات الشراء والمصروفات',
    manageScrapMaterialPurchaseOrders: 'إدارة طلبات شراء مواد الخردة وتتبع التسليمات',
    manageTransportationMaintenance: 'إدارة النقل والصيانة ومصروفات الشراء الأخرى',
    
    // Sales Management - Missing Keys
    salesManagement: 'إدارة المبيعات',
    newSaleOrder: 'طلب بيع جديد',
    salesOrders: 'طلبات البيع',
    invoices: 'الفواتير',
    manageSalesOrders: 'إدارة طلبات البيع والفواتير',
    noInvoicesGenerated: 'لم يتم إنشاء فواتير بعد',
    createSalesOrdersFirst: 'أنشئ طلبات البيع أولاً، ثم أنشئ الفواتير منها',
    pendingOrders: 'الطلبات المعلقة',
    ordersToday: 'الطلبات (اليوم)',
    totalSalesToday: 'إجمالي المبيعات (اليوم)',

    // Material & Inventory - Missing Keys
    materialInventoryManagement: 'إدارة مخزون المواد',
    processmaterials: 'معالجة المواد',
    storageManagement: 'إدارة التخزين',
    
    // Supplier Management - Missing Keys
    supplierManagement: 'إدارة الموردين',
    addSupplier: 'إضافة مورد',
    totalSuppliers: 'إجمالي الموردين',
    supplierSubtitle: '',
    
    // Table Headers and Fields - Missing Keys
    supplier: 'المورد',
    orderId: 'رقم الطلب',
    items: 'العناصر',
    payment: 'الدفع',
    total: 'الإجمالي',
    amount: 'المبلغ',
    description: 'الوصف',
    category: 'الفئة',
    expenseId: 'رقم المصروف',
    customer: 'العميل',
    allCustomers: 'جميع العملاء',
    allStatus: 'جميع الحالات',
    searchSalesOrders: 'البحث في طلبات البيع',
    storageManagement: 'إدارة التخزين',


    // Filter and Search - Missing Keys
    advancedFilters: 'المرشحات المتقدمة',
    columns: 'الأعمدة',
    
    // Dashboard & Analytics
    totalCustomers: 'إجمالي العملاء',
    totalSales: 'إجمالي المبيعات',
    totalPurchases: 'إجمالي المشتريات',
    totalRevenue: 'إجمالي الإيرادات',
    totalProfit: 'إجمالي الربح',
    pendingOrders: 'الطلبات المعلقة',
    completedOrders: 'الطلبات المكتملة',
    lowStock: 'المواد منخفضة المخزون',
    outOfStock: 'نفدت من المخزون',
    recentTransactions: 'المعاملات الأخيرة',
    monthlyRevenue: 'الإيرادات الشهرية',
    weeklyRevenue: 'الإيرادات الأسبوعية',
    dailyRevenue: 'الإيرادات اليومية',
    yearlyRevenue: 'الإيرادات السنوية',
    topCustomers: 'أفضل العملاء',
    topProducts: 'أفضل المنتجات',
    salesGrowth: 'نمو المبيعات',
    
    // Customer Management
    addCustomer: 'إضافة عميل',
    editCustomer: 'تعديل العميل',
    deleteCustomer: 'حذف العميل',
    viewCustomer: 'عرض العميل',
    customerName: 'اسم العميل',
    customerCode: 'كود العميل',
    customerType: 'نوع العميل',
    contactPerson: 'الشخص المسؤول',
    contactNumber: 'رقم الاتصال',
    email: 'البريد الإلكتروني',
    phone: 'الهاتف',
    mobile: 'الجوال',
    fax: 'الفاكس',
    website: 'الموقع الإلكتروني',
    address: 'العنوان',
    street: 'الشارع',
    city: 'المدينة',
    state: 'الولاية',
    country: 'البلد',
    postalCode: 'الرمز البريدي',
    creditLimit: 'حد الائتمان',
    creditUsed: 'الائتمان المستخدم',
    creditAvailable: 'الائتمان المتاح',
    paymentTerms: 'شروط الدفع',
    customerDetails: 'تفاصيل العميل',
    customerHistory: 'تاريخ العميل',
    customerBalance: 'رصيد العميل',
    createOrder: 'إنشاء طلب',
    viewContract: 'عرض العقد',
    customerList: 'قائمة العملاء',
    
    // Supplier Management
    addSupplier: 'إضافة مورد',
    editSupplier: 'تعديل المورد',
    deleteSupplier: 'حذف المورد',
    viewSupplier: 'عرض المورد',
    supplierName: 'اسم المورد',
    supplierCode: 'كود المورد',
    supplierType: 'نوع المورد',
    supplierDetails: 'تفاصيل المورد',
    supplierHistory: 'تاريخ المورد',
    supplierBalance: 'رصيد المورد',
    supplierList: 'قائمة الموردين',
    specialization: 'التخصص',
    monthlyRevenue: 'الإيرادات الشهرية',
    weeklyRevenue: 'الإيرادات الأسبوعية',
    businessPartners: 'شركاء الأعمال',
    regularPartners: 'الشركاء المنتظمون',
    businessSuppliers: 'موردي الأعمال',
    activeSuppliers: 'الموردين النشطين',
    inactiveSuppliers: 'الموردين غير النشطين',
    manageScrapSuppliers: 'إدارة موردي الخردة',
    addNewSupplier: 'إضافة مورد جديد',
    supplierCreated: 'تم إنشاء المورد بنجاح!',
    supplierUpdated: 'تم تحديث المورد بنجاح!',
    supplierDeleted: 'تم حذف المورد بنجاح!',
    createNewContract: 'إنشاء عقد جديد',
    renewContract: 'تجديد العقد',
    editContract: 'تعديل العقد',
    
    // Inventory Management
    addMaterial: 'إضافة مادة',
    editMaterial: 'تعديل المادة',
    deleteMaterial: 'حذف المادة',
    viewMaterial: 'عرض المادة',
    materialName: 'اسم المادة',
    materialCode: 'كود المادة',
    materialType: 'نوع المادة',
    category: 'الفئة',
    subcategory: 'الفئة الفرعية',
    brand: 'العلامة التجارية',
    model: 'الطراز',
    specification: 'المواصفات',
    description: 'الوصف',
    unit: 'الوحدة',
    unitPrice: 'سعر الوحدة',
    currentStock: 'المخزون الحالي',
    minimumStock: 'الحد الأدنى للمخزون',
    maximumStock: 'الحد الأقصى للمخزون',
    reorderLevel: 'مستوى إعادة الطلب',
    standardPrice: 'السعر القياسي',
    sellingPrice: 'سعر البيع',
    purchasePrice: 'سعر الشراء',
    supplier: 'المورد',
    location: 'الموقع',
    warehouse: 'المستودع',
    shelf: 'الرف',
    lastUpdated: 'آخر تحديث',
    stockMovement: 'حركة المخزون',
    stockIn: 'وارد',
    stockOut: 'صادر',
    stockAdjustment: 'تسوية المخزون',
    startSorting: 'بدء الفرز',
    stopSorting: 'إيقاف الفرز',
    checkProgress: 'مراجعة التقدم',
    weight: 'الوزن',
    gradePurity: 'درجة النقاء',
    purchaseRate: 'سعر الشراء',
    sellingRate: 'سعر البيع',
    marketRate: 'السعر السوقي',
    currentValue: 'القيمة الحالية',
    potentialProfit: 'الربح المحتمل',
    inventoryOverview: 'نظرة عامة على المخزون',
    completeInventorySummary: 'ملخص كامل للمخزون',
    materialInventoryManagementTitle: '',
    materialInventorySubtitle: 'تتبع مخزون المواد والمعالجة',
    stockMovementsSubtitle: 'تتبع حركات الوارد والصادر من المخزون',
    readyToSell: 'جاهز للبيع',
    sortingRequired: 'يتطلب فرز',
    sellNow: 'بيع الآن',
    goodStock: 'مخزون جيد',
    critical: 'حرج',
    outOfStock: 'نفد من المخزون',
    noCustomersFound: 'لم يتم العثور على عملاء',
    noContractsFound: 'لم يتم العثور على عقود',
    noMaterialsFound: 'لم يتم العثور على مواد',
    noMovementsFound: 'لم يتم العثور على حركات مخزون',
    noSuppliersFound: 'لم يتم العثور على موردين',
    loadingContracts: 'جاري تحميل العقود...',
    trackScrapMaterialsSubtitle: '',
    trackStockLevelsSubtitle: '',
    processMaterialsSubtitle: '',
    potentialProfit: '',
    
    // Sales & Purchase Orders
    addOrder: 'إضافة طلب',
    editOrder: 'تعديل الطلب',
    deleteOrder: 'حذف الطلب',
    viewOrder: 'عرض الطلب',
    orderNumber: 'رقم الطلب',
    orderDate: 'تاريخ الطلب',
    deliveryDate: 'تاريخ التسليم',
    expectedDelivery: 'التسليم المتوقع',
    orderStatus: 'حالة الطلب',
    orderType: 'نوع الطلب',
    salesOrder: 'طلب بيع',
    purchaseOrder: 'طلب شراء',
    quotation: 'عرض سعر',
    invoice: 'فاتورة',
    receipt: 'إيصال',
    delivery: 'التسليم',
    quantity: 'الكمية',
    rate: 'السعر',
    discount: 'الخصم',
    amount: 'المبلغ',
    subtotal: 'المجموع الفرعي',
    tax: 'الضريبة',
    taxRate: 'معدل الضريبة',
    taxAmount: 'مبلغ الضريبة',
    total: 'الإجمالي',
    grandTotal: 'المجموع الكلي',
    netTotal: 'الصافي',
    balance: 'الرصيد',
    due: 'مستحق',
    advance: 'مقدم',
    orderItems: 'عناصر الطلب',
    
    // Contracts
    addContract: 'إضافة عقد',
    editContract: 'تعديل العقد',
    deleteContract: 'حذف العقد',
    contractNumber: 'رقم العقد',
    contractName: 'اسم العقد',
    contractType: 'نوع العقد',
    contractValue: 'قيمة العقد',
    contractPeriod: 'مدة العقد',
    startDate: 'تاريخ البداية',
    endDate: 'تاريخ النهاية',
    renewalDate: 'تاريخ التجديد',
    contractStatus: 'حالة العقد',
    contractTerms: 'شروط العقد',
    specialTerms: 'الشروط الخاصة',
    deliveryTerms: 'شروط التسليم',
    contractRates: 'أسعار العقد',
    fixedRate: 'سعر ثابت',
    discountRate: 'سعر الخصم',
    minimumGuarantee: 'الحد الأدنى المضمون',
    contractExpiry: 'انتهاء العقد',
    activeContract: 'عقد نشط',
    expiredContract: 'عقد منتهي',
    
    // Financial Terms
    payment: 'الدفع',
    paymentMethod: 'طريقة الدفع',
    paymentStatus: 'حالة الدفع',
    paymentDate: 'تاريخ الدفع',
    dueDate: 'تاريخ الاستحقاق',
    cash: 'نقدي',
    credit: 'ائتمان',
    cheque: 'شيك',
    bankTransfer: 'تحويل بنكي',
    card: 'بطاقة',
    expense: 'مصروف',
    income: 'دخل',
    profit: 'ربح',
    loss: 'خسارة',
    revenue: 'إيراد',
    cost: 'تكلفة',
    margin: 'هامش',
    commission: 'عمولة',
    
    // Settings & Configuration
    generalSettings: 'الإعدادات العامة',
    localizationSettings: 'إعدادات التوطين',
    systemSettings: 'إعدادات النظام',
    userSettings: 'إعدادات المستخدم',
    companySettings: 'إعدادات الشركة',
    language: 'اللغة',
    dateFormat: 'تنسيق التاريخ',
    timeFormat: 'تنسيق الوقت',
    numberFormat: 'تنسيق الأرقام',
    currency: 'العملة',
    timezone: 'المنطقة الزمنية',
    firstDayOfWeek: 'أول يوم في الأسبوع',
    fiscalYear: 'السنة المالية',
    appearance: 'المظهر',
    theme: 'السمة',
    lightTheme: 'السمة الفاتحة',
    darkTheme: 'السمة المظلمة',
    notifications: 'الإشعارات',
    
    // User Management & Roles
    username: 'اسم المستخدم',
    password: 'كلمة المرور',
    confirmPassword: 'تأكيد كلمة المرور',
    currentPassword: 'كلمة المرور الحالية',
    newPassword: 'كلمة المرور الجديدة',
    role: 'الدور',
    vatRegistrationNumber: 'رقم التسجيل الضريبي',
    
    // Inventory Management
    openingStock: 'المخزون الافتتاحي',
    openingStockValue: 'قيمة المخزون الافتتاحي',
    openingStockDate: 'تاريخ المخزون الافتتاحي',
    setOpeningStock: 'تحديد المخزون الافتتاحي',
    showCharts: 'إظهار المخططات',
    hideCharts: 'إخفاء المخططات',
    selectMaterial: 'اختر المادة',
    currentOpeningStock: 'المخزون الافتتاحي الحالي',
    updateOpeningStock: 'تحديث المخزون الافتتاحي',
    openingStockUpdated: 'تم تحديث المخزون الافتتاحي بنجاح',
    barChart: 'المخطط العمودي',
    lineChart: 'المخطط الخطي',
    pieChart: 'المخطط الدائري',
    
    // Wastage Management
    wastageManagement: 'إدارة النفايات والخسائر',
    trackWastageAndLosses: 'تتبع نفايات وخسائر المواد',
    reportWastage: 'الإبلاغ عن نفايات',
    viewAnalytics: 'عرض التحليلات',
    totalWastages: 'إجمالي النفايات',
    totalWasteCost: 'إجمالي تكلفة النفايات',
    pendingApproval: 'في انتظار الموافقة',
    approved: 'تمت الموافقة',
    rejected: 'مرفوض',
    wasteType: 'نوع النفايات',
    wastageRecords: 'سجلات النفايات',
    noWastageRecords: 'لم يتم العثور على سجلات نفايات',
    wastageAnalytics: 'تحليلات النفايات',
    wastageByType: 'النفايات حسب النوع',
    monthlyWastageTrends: 'اتجاهات النفايات الشهرية',
    loadingWastageData: 'جاري تحميل بيانات النفايات...',
    allTypes: 'جميع الأنواع',
    totalCost: 'التكلفة الإجمالية',
    permissions: 'الصلاحيات',
    company: 'الشركة',
    department: 'القسم',
    position: 'المنصب',
    lastLogin: 'آخر تسجيل دخول',
    loginTime: 'وقت تسجيل الدخول',
    logoutTime: 'وقت تسجيل الخروج',
    userManagement: 'إدارة المستخدمين',
    addUser: 'إضافة مستخدم',
    editUser: 'تعديل المستخدم',
    deleteUser: 'حذف المستخدم',
    viewUser: 'عرض المستخدم',
    userProfile: 'ملف المستخدم',
    changePassword: 'تغيير كلمة المرور',
    
    // Time & Date
    today: 'اليوم',
    yesterday: 'أمس',
    tomorrow: 'غداً',
    thisWeek: 'هذا الأسبوع',
    lastWeek: 'الأسبوع الماضي',
    nextWeek: 'الأسبوع القادم',
    thisMonth: 'هذا الشهر',
    lastMonth: 'الشهر الماضي',
    nextMonth: 'الشهر القادم',
    thisYear: 'هذا العام',
    lastYear: 'العام الماضي',
    nextYear: 'العام القادم',
    morning: 'الصباح',
    afternoon: 'بعد الظهر',
    evening: 'المساء',
    night: 'الليل',
    
    // Validation Messages
    required: 'هذا الحقل مطلوب',
    invalidEmail: 'يرجى إدخال عنوان بريد إلكتروني صحيح',
    invalidPhone: 'يرجى إدخال رقم هاتف صحيح',
    invalidDate: 'يرجى إدخال تاريخ صحيح',
    invalidNumber: 'يرجى إدخال رقم صحيح',
    minLength: 'مطلوب حد أدنى {min} أحرف',
    maxLength: 'الحد الأقصى {max} حرف مسموح',
    minValue: 'القيمة الدنيا المسموحة {min}',
    maxValue: 'القيمة العليا المسموحة {max}',
    passwordMismatch: 'كلمات المرور غير متطابقة',
    passwordTooWeak: 'كلمة المرور ضعيفة جداً',
    fieldRequired: 'الحقل مطلوب',
    pleaseSelect: 'يرجى الاختيار',
    pleaseEnter: 'يرجى الإدخال',
    confirmDelete: 'هل أنت متأكد أنك تريد حذف هذا العنصر؟',
    errorDeleting: 'خطأ في حذف العنصر',
    errorSaving: 'خطأ في حفظ البيانات',
    fillRequiredFields: 'يرجى ملء جميع الحقول المطلوبة',
    
    // Success Messages
    saveSuccess: 'تم الحفظ بنجاح',
    updateSuccess: 'تم التحديث بنجاح',
    deleteSuccess: 'تم الحذف بنجاح',
    addSuccess: 'تم الإضافة بنجاح',
    createSuccess: 'تم الإنشاء بنجاح',
    customerAdded: 'تم إضافة العميل بنجاح',
    customerUpdated: 'تم تحديث العميل بنجاح',
    customerDeleted: 'تم حذف العميل بنجاح',
    orderCreated: 'تم إنشاء الطلب بنجاح',
    orderUpdated: 'تم تحديث الطلب بنجاح',
    contractCreated: 'تم إنشاء العقد بنجاح',
    contractUpdated: 'تم تحديث العقد بنجاح',
    settingsSaved: 'تم حفظ الإعدادات بنجاح',
    passwordChanged: 'تم تغيير كلمة المرور بنجاح',
    profileUpdated: 'تم تحديث الملف الشخصي بنجاح',
    
    // Error Messages
    somethingWentWrong: 'حدث خطأ ما. يرجى المحاولة مرة أخرى.',
    networkError: 'خطأ في الشبكة. يرجى التحقق من الاتصال.',
    serverError: 'خطأ في الخادم. يرجى المحاولة لاحقاً.',
    unauthorized: 'غير مخول لك لأداء هذا الإجراء.',
    accessDenied: 'تم رفض الوصول',
    notFound: 'غير موجود',
    alreadyExists: 'موجود بالفعل',
    invalidCredentials: 'بيانات الاعتماد غير صحيحة',
    sessionExpired: 'انتهت صلاحية الجلسة',
    operationFailed: 'فشلت العملية',
    dataCorrupted: 'البيانات تالفة',
    insufficientPermissions: 'صلاحيات غير كافية',
    
    // Business Specific
    oilTrading: 'تجارة النفط',
    scrapMaterials: 'مواد الخردة',
    fuelInventory: 'مخزون الوقود',
    materialInventory: 'مخزون المواد',
    tankCapacity: 'سعة الخزان',
    currentLevel: 'المستوى الحالي',
    materialGrade: 'درجة المادة',
    weightPerUnit: 'الوزن لكل وحدة',
    fuelType: 'نوع الوقود',
    oilType: 'نوع النفط',
    viscosity: 'اللزوجة',
    density: 'الكثافة',
    purity: 'النقاء',
    grade: 'الدرجة',
    quality: 'الجودة',
    barrel: 'برميل',
    liter: 'لتر',
    gallon: 'جالون',
    ton: 'طن',
    kilogram: 'كيلوغرام',
    gram: 'غرام',
    meter: 'متر',
    centimeter: 'سنتيمتر',
    monthlyVolume: 'الحجم الشهري',
    weeklyVolume: 'الحجم الأسبوعي',
    dailyVolume: 'الحجم اليومي',
    yearlyVolume: 'الحجم السنوي',
    totalValue: 'القيمة الإجمالية',
    totalVolume: 'الحجم الإجمالي',
    totalCollected: 'إجمالي المحصل',
    totalPending: 'إجمالي المعلق',
    advancedFilters: 'المرشحات المتقدمة',
    advancedSearch: 'البحث المتقدم',
    viewDetails: 'عرض التفاصيل',
    walkIn: 'زبون عادي',
    project: 'مشروع',
    totalProfit: 'إجمالي الربح',
    topCustomers: 'أفضل العملاء',
    topProducts: 'أفضل المنتجات',
    salesGrowth: 'نمو المبيعات',
    
    // Page Headers and Titles
    customerManagementTitle: 'إدارة العملاء',
    contractManagementTitle: 'إدارة العقود',
    purchaseOrdersTitle: 'أوامر الشراء', 
    inventoryManagementTitle: 'إدارة المخزون',
    supplierManagementTitle: 'إدارة الموردين',
    materialInventoryManagementTitle: 'إدارة مخزون المواد',
    
    // Subtitles and Descriptions
    manageFuelCustomersSubtitle: 'إدارة عملاء الوقود وعقود التسليم',
    manageFuelContractsSubtitle: 'إدارة عقود توريد الوقود والاتفاقيات',
    manageVendorOrdersSubtitle: 'إدارة أوامر الموردين والمشتريات لـ',
    trackStockLevelsSubtitle: 'تتبع مستويات المخزون والحركات والحالة',
    trackScrapMaterialsSubtitle: 'تتبع مواد الخردة والتخزين وحالة المعالجة',
    
    // Button Labels
    addCustomerBtn: 'إضافة عميل',
    newContractBtn: 'عقد جديد',
    newPurchaseOrderBtn: 'أمر شراء جديد',
    stockReportBtn: 'تقرير المخزون',
    stockAdjustmentBtn: 'تعديل المخزون',
    processMaterialsBtn: 'معالجة المواد',
    addSupplierBtn: 'إضافة مورد',
    processMaterialsBtn: '',
    
    // Loading Messages
    loadingCustomers: 'جاري تحميل العملاء...',
    loadingSuppliers: 'جاري تحميل الموردين...',
    loadingPurchaseOrders: 'جاري تحميل أوامر الشراء...',
    loadingInventory: 'جاري تحميل المخزون...',
    
    // Dashboard Cards
    activeContracts: 'العقود النشطة',
    expiringSoon: 'تنتهي قريباً',
    pendingRenewal: 'في انتظار التجديد',
    currentlyRunning: 'قيد التشغيل حالياً',
    withinDays: 'خلال 30 يوم',
    actionRequired: 'يتطلب إجراء',
    
    // Form Section Headers
    basicInformation: 'المعلومات الأساسية',
    contactInformation: 'معلومات الاتصال',
    addressInformation: 'معلومات العنوان',
    businessTerms: 'الشروط التجارية',
    businessDetails: 'تفاصيل العمل',
    contractTermsConditions: 'شروط وأحكام العقد',
    orderInformation: 'معلومات الطلب',
    customerDetails: 'تفاصيل العميل',
    vendorInformation: 'معلومات المورد',
    materialRatesPricing: 'أسعار المواد والتسعير',
    orderItems: 'عناصر الطلب',
    orderTotals: 'إجماليات الطلب',
    additionalInformation: 'معلومات إضافية',
    bankingInformation: 'المعلومات المصرفية',
    
    // Form Field Labels
    customerNameRequired: 'اسم العميل *',
    customerTypeRequired: 'نوع العميل *',
    contactPersonLabel: 'الشخص المسؤول',
    phoneNumberRequired: 'رقم الهاتف *',
    emailAddress: 'عنوان البريد الإلكتروني',
    streetAddress: 'عنوان الشارع',
    cityLabel: 'المدينة',
    regionLabel: 'المنطقة',
    creditLimitOMR: 'حد الائتمان (ريال عماني)',
    paymentTermsDays: 'شروط الدفع (أيام)',
    specialTermsConditions: 'الشروط والأحكام الخاصة',
    supplierCodeRequired: 'كود المورد *',
    supplierNameRequired: 'اسم المورد *',
    supplierTypeLabel: 'نوع المورد',
    businessRegistration: 'السجل التجاري',
    nationalIdLabel: 'الهوية الوطنية',
    taxNumberLabel: 'الرقم الضريبي',
    bankNameLabel: 'اسم البنك',
    accountNumberLabel: 'رقم الحساب',
    ibanLabel: 'الآيبان',
    
    // Modal Titles
    editCustomerModal: 'تعديل العميل',
    addNewCustomerModal: 'إضافة عميل جديد',
    customerDetailsModal: 'تفاصيل العميل',
    contractDetailsModal: 'تفاصيل العقد',
    editContractModal: 'تعديل العقد',
    createNewContractModal: 'إنشاء عقد جديد',
    addNewSupplierModal: 'إضافة مورد جديد',
    editSupplierModal: 'تعديل المورد',
    supplierDetailsModal: 'تفاصيل المورد',
    createSalesOrderModal: 'إنشاء أمر مبيعات',
    createPurchaseOrderModal: 'إنشاء أمر شراء',
    
    // Status Labels
    readyToSellStatus: 'جاهز للبيع',
    processingStatus: 'قيد المعالجة',
    sortingRequiredStatus: 'يتطلب فرز',
    contractCustomer: 'عميل عقد',
    highValueStatus: 'قيمة عالية',
    lowStockStatus: 'مخزون منخفض',
    criticalStatus: 'حرج',
    goodStockStatus: 'مخزون جيد',
    
    // Action Buttons
    viewDetailsBtn: 'عرض التفاصيل',
    sellNowBtn: 'بيع الآن',
    checkProgressBtn: 'مراجعة التقدم',
    startSortingBtn: 'بدء الفرز',
    createOrderBtn: 'إنشاء طلب',
    viewContractBtn: 'عرض العقد',
    renewContractBtn: 'تجديد العقد',
    manageSectionsBtn: 'إدارة الأقسام',
    optimizeLayoutBtn: 'تحسين التخطيط',
    
    // Table Column Headers
    orderNumberHeader: 'رقم الطلب',
    vendorHeader: 'المورد',
    expectedDeliveryHeader: 'التسليم المتوقع',
    itemsHeader: 'العناصر',
    totalAmountHeader: 'المبلغ الإجمالي',
    materialHeader: 'المادة',
    weightHeader: 'الوزن',
    gradePurityHeader: 'درجة النقاء',
    purchaseRateHeader: 'سعر الشراء',
    marketRateHeader: 'السعر السوقي',
    currentValueHeader: 'القيمة الحالية',
    potentialProfitHeader: 'الربح المحتمل',
    
    // Inventory Categories
    engineOils: 'زيوت المحركات',
    diesel: 'الديزل',
    emptyDrums: 'البراميل الفارغة',
    crudeSludge: 'الحمأة الخام',
    
    // Material Grades
    commercialGrade: 'درجة تجارية',
    premiumUnleaded: 'ممتاز خالي من الرصاص',
    multiGrade: 'متعدد الدرجات',
    gradeA: 'الدرجة أ',
    recycled: 'معاد تدويره',
    mixedGrade: 'درجة مختلطة',
    clean: 'نظيف',
    
    // Time and Date
    todayTime: 'اليوم',
    yesterdayTime: 'أمس',
    timeAgo: 'منذ',
    
    // Units and Measurements
    litersUnit: 'لتر',
    kilogramsUnit: 'كيلو',
    piecesUnit: 'قطعة',
    capacityUnit: 'السعة',
    perLiter: 'لكل لتر',
    perBarrel: 'لكل برميل',
    perKilogram: 'لكل كيلوغرام',
    
    // Alerts and Messages
    lowStockAlert: 'تنبيه مخزون منخفض',
    storageCapacityAlert: 'تنبيه سعة التخزين',
    marketUpdate: 'تحديث السوق',
    noContractFound: 'لم يتم العثور على عقد',
    noSpecialRatesConfigured: 'لم يتم إعداد أسعار خاصة',
    noMaterialRatesAdded: 'لم يتم إضافة أسعار مواد',
    accessDeniedMessage: 'الوصول مرفوض',
    permissionDeniedMessage: 'ليس لديك إذن للوصول إلى إعدادات النظام.',
    
    // Contract Types
    fuelSupplyContract: 'عقد توريد الوقود',
    bulkSupplyContract: 'عقد التوريد بالجملة',
    exclusiveSupplyContract: 'عقد التوريد الحصري',
    projectBasedContract: 'عقد قائم على المشروع',
    
    // Payment Terms
    net15Days: 'صافي 15 يوم',
    net30Days: 'صافي 30 يوم',
    net45Days: 'صافي 45 يوم',
    net60Days: 'صافي 60 يوم',
    cashOnDelivery: 'دفع عند التسليم',
    advancePayment: 'دفع مقدم',
    
    // Specialization Options
    copper: 'النحاس',
    aluminum: 'الألومنيوم',
    steel: 'الفولاذ',
    iron: 'الحديد',
    brass: 'النحاس الأصفر',
    electronics: 'الإلكترونيات',
    preciousMetals: 'المعادن النفيسة',
    cables: 'الكابلات',
    
    // Collection Areas
    muscat: 'مسقط',
    bawshar: 'بوشر',
    ruwi: 'روي',
    mutrah: 'مطرح',
    seeb: 'السيب',
    alKhuwair: 'الخوير',
    sohar: 'صحار',
    
    // Performance Metrics
    reliabilityScore: 'نقاط الموثوقية',
    qualityRating: 'تقييم الجودة',
    averageRate: 'متوسط السعر',
    notSpecified: 'غير محدد',
    notProvided: 'غير مقدم',
    
    // Tab Labels
    overviewTab: 'نظرة عامة',
    materialsTab: 'المواد',
    stockMovementsTab: 'حركات المخزون',
    materialsInventoryTab: 'مخزون المواد',
    storageManagementTab: 'إدارة التخزين',
    
    // Form Placeholders
    enterCustomerName: 'أدخل اسم العميل',
    enterContactPerson: 'أدخل اسم الشخص المسؤول',
    enterStreetAddress: 'أدخل عنوان الشارع',
    enterCity: 'أدخل المدينة',
    enterRegion: 'أدخل المنطقة/المحافظة',
    selectCustomer: 'اختر عميل...',
    selectMaterial: 'اختر مادة...',
    selectVendor: 'اختر مورد...',
    
    // Confirmation Messages
    confirmDeleteCustomer: 'هل أنت متأكد أنك تريد حذف هذا العميل؟',
    confirmDeleteSupplier: 'هل أنت متأكد أنك تريد حذف هذا المورد؟',
    confirmDeleteContract: 'هل أنت متأكد أنك تريد حذف هذا العقد؟',
    
    // Missing keys currently used in code - Arabic translations
    generateInvoice: 'إنشاء فاتورة',
    noOrdersFound: 'لم يتم العثور على طلبات',
    orderId: 'رقم الطلب',
    adjustStock: 'تعديل المخزون',
    viewHistory: 'عرض التاريخ',
    purchaseOrders: 'أوامر الشراء',
    editPurchaseOrder: 'تعديل أمر الشراء',
    createPurchaseOrder: 'إنشاء أمر شراء',
    noPurchaseOrdersFound: 'لم يتم العثور على أوامر شراء',
    adjustStockLevel: 'تعديل مستوى المخزون',
    stockMovements: 'حركات المخزون',
    storageManagement: 'إدارة التخزين',
    materialInventoryManagement: 'إدارة مخزون المواد',
    trackMaterialInventory: 'تتبع مخزون المواد والمعالجة',
    processInventory: 'معالجة المخزون',
    optimizeStorage: 'تحسين التخزين',
    download: 'تحميل',
    approve: 'الموافقة',
    orderStatus: 'حالة الطلب',
    orderNotes: 'ملاحظات الطلب',
    contractRate: 'سعر العقد',
    createSalesOrder: 'إنشاء أمر مبيعات',
    expectedDeliveryDate: 'تاريخ التسليم المتوقع',
    specialInstructions: 'تعليمات خاصة',
    rateOverrideRequired: 'يتطلب تجاوز السعر',
    managerApprovalNeeded: 'يتطلب موافقة المدير لتغيير السعر المتعاقد عليه',
    salesHistory: 'تاريخ المبيعات',
    contractInformation: 'معلومات العقد',
    businessInformation: 'معلومات الأعمال',
    performanceMetrics: 'مقاييس الأداء',
    purchaseHistory: 'تاريخ المشتريات',
    totalMaterialWeight: 'إجمالي وزن المواد',
    totalInventoryValue: 'إجمالي قيمة المخزون',
    storageLocationsOverview: 'نظرة عامة على مواقع التخزين',
    
    // Additional commonly used keys - Arabic translations
    items: 'العناصر',
    payment: 'الدفع',
    supplier: 'المورد',
    customer: 'العميل',
    order: 'الطلب',
    orders: 'الطلبات',
    suppliers: 'الموردين',
    customers: 'العملاء',
    materials: 'المواد',
    inventory: 'المخزون',
    purchase: 'الشراء',
    sales: 'المبيعات',
    contracts: 'العقود',
    reports: 'التقارير',
    settings: 'الإعدادات',
    profile: 'الملف الشخصي',
    logout: 'تسجيل الخروج',
    home: 'الرئيسية',
    
    // Welcome and greeting messages
    welcomeBack: 'مرحباً بعودتك',
    welcomeTo: 'مرحباً بك في',
    goodMorning: 'صباح الخير',
    goodAfternoon: 'مساء الخير',
    goodEvening: 'مساء الخير',
    
    // Statistical and percentage text
    fromLastMonth: 'من الشهر الماضي',
    fromLastWeek: 'من الأسبوع الماضي',
    fromYesterday: 'من أمس',
    increase: 'زيادة',
    decrease: 'انخفاض',
    noChange: 'لا تغيير',
    percentage: 'نسبة مئوية',
    
    // Time periods
    hourAgo: 'منذ ساعة',
    hoursAgo: 'منذ {hours} ساعات',
    minuteAgo: 'منذ دقيقة',
    minutesAgo: 'منذ {minutes} دقائق',
    dayAgo: 'منذ يوم',
    daysAgo: 'منذ {days} أيام',
    weekAgo: 'منذ أسبوع',
    weeksAgo: 'منذ {weeks} أسابيع',
    yearToDate: 'من بداية السنة حتى الآن',
    thisWeek: 'هذا الأسبوع',
    lastWeek: 'الأسبوع الماضي',
    nextWeek: 'الأسبوع القادم',
    thisMonth: 'هذا الشهر',
    nextMonth: 'الشهر القادم',
    thisYear: 'هذا العام',
    nextYear: 'العام القادم',
    morning: 'الصباح',
    night: 'الليل',
    
    // Professional settings terms
    systemConfiguration: 'إعدادات النظام',
    systemPreferences: 'تفضيلات النظام',
    configureGlobalSettings: 'إعداد الإعدادات العامة',
    configureLanguageAndRegion: 'إعداد اللغة والمنطقة',
    configureCulturalPreferences: 'إعداد التفضيلات الثقافية',
    languagePreferenceSavedPerUser: 'تفضيل اللغة محفوظ لكل مستخدم',
    currentSettingsInformation: 'معلومات الإعدادات الحالية',
    settingsSource: 'مصدر الإعدادات',
    isCustomized: 'مخصص',
    resetToDefaults: 'إعادة تعيين إلى الافتراضي',
    saveSettings: 'حفظ الإعدادات',
    saving: 'جاري الحفظ...',
    appearanceSettings: 'إعدادات المظهر',
    customizeVisualAppearance: 'تخصيص المظهر المرئي',
    notificationSettings: 'إعدادات الإشعارات',
    configureNotificationsAndAlerts: 'إعداد الإشعارات والتنبيهات',
    notificationPreferences: 'تفضيلات الإشعارات',
    availableInFutureUpdate: 'متاح في تحديث مستقبلي',
    
    // Dashboard specific terms
    manageBusinessCustomersAndContacts: 'إدارة عملاء الأعمال وجهات الاتصال',
    manageFuelCustomersAndContracts: 'إدارة عملاء الوقود وعقود التسليم',
    trackStockLevelsAndMovements: 'تتبع مستويات المخزون والحركات',
    manageSalesOrdersAndInvoices: 'إدارة أوامر المبيعات والفواتير',
    managePurchaseOrdersAndExpenses: 'إدارة أوامر الشراء والمصروفات',
    
    // Miscellaneous
    all: 'الكل',
    none: 'لا شيء',
    other: 'أخرى',
    unknown: 'غير معروف',
    notApplicable: 'غير قابل للتطبيق',
    notAvailable: 'غير متاح',
    comingSoon: 'قريباً',
    underConstruction: 'قيد الإنشاء',
    maintenance: 'صيانة',
    upgrade: 'ترقية',
    version: 'الإصدار',
    about: 'حول',
    help: 'مساعدة',
    support: 'الدعم',
    contact: 'اتصل بنا',
    privacy: 'الخصوصية',
    terms: 'الشروط',
    legal: 'قانوني',
    copyright: 'حقوق الطبع والنشر',
    status: 'الحالة',
    action: 'الإجراء',
    reference: 'المرجع',
    description: 'الوصف',
    details: 'تفاصيل',
  }
}

export const LocalizationProvider = ({ children }) => {
  const { user } = useAuth()
  const [currentLanguage, setCurrentLanguage] = useState('en')
  const [direction, setDirection] = useState('ltr')

  // Load language preference
  useEffect(() => {
    // Check for user preference first
    const userLanguage = localStorage.getItem(`user_language_${user?.id}`)
    if (userLanguage) {
      setCurrentLanguage(userLanguage)
    } else {
      // Fallback to global setting or browser language
      const globalLanguage = localStorage.getItem('global_app_language')
      if (globalLanguage) {
        setCurrentLanguage(globalLanguage)
      } else {
        // Fallback to browser language or default
        const browserLang = navigator.language.split('-')[0]
        const supportedLang = ['en', 'ar'].includes(browserLang) ? browserLang : 'en'
        setCurrentLanguage(supportedLang)
      }
    }
  }, [user?.id])

  // Update direction based on language
  useEffect(() => {
    const isRTL = currentLanguage === 'ar'
    setDirection(isRTL ? 'rtl' : 'ltr')
    
    // Update document direction and language
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr'
    document.documentElement.lang = currentLanguage
    
    // Update body class for RTL styling
    document.body.className = document.body.className
      .replace(/\b(rtl|ltr)\b/g, '')
      .trim() + ` ${isRTL ? 'rtl' : 'ltr'}`
  }, [currentLanguage])

  // Change language (users can set their own preference)
  const changeLanguage = (language) => {
    setCurrentLanguage(language)
    
    if (user) {
      // Save user preference
      localStorage.setItem(`user_language_${user.id}`, language)
      
      // If Super Admin, also update global default
      if (user.role === 'SUPER_ADMIN') {
        localStorage.setItem('global_app_language', language)
      }
    }
    
    // Could also sync to server for cross-device consistency
    // await syncLanguageToServer(language)
  }

  // Get translation with fallback
  const t = (key, params = {}) => {
    let translation = translations[currentLanguage]?.[key] || translations.en[key] || key
    
    // Replace parameters in translation
    Object.keys(params).forEach(param => {
      translation = translation.replace(`{${param}}`, params[param])
    })
    
    return translation
  }

  // Get translation for interpolated strings
  const tr = (key, params = {}) => t(key, params)

  // Check if current language is RTL
  const isRTL = () => currentLanguage === 'ar'

  // Get supported languages
  const getSupportedLanguages = () => [
    { code: 'en', name: 'English', nativeName: 'English' },
    { code: 'ar', name: 'Arabic', nativeName: 'العربية' }
  ]

  // Format number based on locale
  const formatNumber = (number, options = {}) => {
    const locale = currentLanguage === 'ar' ? 'ar-SA' : 'en-US'
    return new Intl.NumberFormat(locale, options).format(number)
  }

  // Format currency based on locale
  const formatCurrency = (amount, currency = 'OMR') => {
    const locale = currentLanguage === 'ar' ? 'ar-SA' : 'en-US'
    return new Intl.NumberFormat(locale, {
      style: 'currency',
      currency: currency,
      minimumFractionDigits: 3,
      maximumFractionDigits: 3
    }).format(amount)
  }

  const value = {
    currentLanguage,
    direction,
    isRTL: isRTL(),
    changeLanguage,
    getSupportedLanguages,
    t,
    tr,
    formatNumber,
    formatCurrency
  }

  return (
    <LocalizationContext.Provider value={value}>
      {children}
    </LocalizationContext.Provider>
  )
}

export default LocalizationProvider